### ISSUE TITLE
ReplicatedSummingMergeTree does not work as expected

### ISSUE THREAD

**Issue by remenska** [yandex/ClickHouse#1009]
Hi Clickhouse devs,
Seems like the SummingMergeTree does work correctly, but if I try the replicated version, I don't get the summary expected.

To reproduce:

```
CREATE TABLE shard_3.replicated_summing_merge_tree_with_list_of_columns_to_sum (d Date, a String, b UInt8, x String, y Int8, z UInt32) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/3/replicated_summing_merge_tree_with_list_of_columns_to_sum/', 'clickhouse003', d, (a, b), 111, (y, z));
```

```
INSERT INTO shard_3.replicated_summing_merge_tree_with_list_of_columns_to_sum VALUES ('2000-01-01', 'Hello, world!', 123, 'xxx yyy', 100, 123489);
INSERT INTO shard_3.replicated_summing_merge_tree_with_list_of_columns_to_sum VALUES ('2000-01-01', 'Hello, world!', 123, 'xxx yyy', -123, 123456789);
```

```
optimize table shard_3.replicated_summing_merge_tree_with_list_of_columns_to_sum
```

```
SELECT *
FROM shard_3.replicated_summing_merge_tree_with_list_of_columns_to_sum

┌──────────d─┬─a─────────────┬───b─┬─x───────┬───y─┬──────z─┐
│ 2000-01-01 │ Hello, world! │ 123 │ xxx yyy │ 100 │ 123489 │
└────────────┴───────────────┴─────┴─────────┴─────┴────────┘
┌──────────d─┬─a─────────────┬───b─┬─x───────┬────y─┬─────────z─┐
│ 2000-01-01 │ Hello, world! │ 123 │ xxx yyy │ -123 │ 123456789 │
└────────────┴───────────────┴─────┴─────────┴──────┴───────────┘

2 rows in set. Elapsed: 0.003 sec.
```

Columns `y` and `z` should be summed up, right?

That's what I get with SummingMergeTree:

```
:) select * from summing_merge_tree_with_list_of_columns_to_sum

SELECT *
FROM summing_merge_tree_with_list_of_columns_to_sum

┌──────────d─┬─a─────────────┬───b─┬─x───────┬───y─┬──────z─┐
│ 2000-01-01 │ Hello, world! │ 123 │ xxx yyy │ 100 │ 123489 │
└────────────┴───────────────┴─────┴─────────┴─────┴────────┘
┌──────────d─┬─a─────────────┬───b─┬─x───────┬────y─┬─────────z─┐
│ 2000-01-01 │ Hello, world! │ 123 │ xxx yyy │ -123 │ 123456789 │
└────────────┴───────────────┴─────┴─────────┴──────┴───────────┘

2 rows in set. Elapsed: 0.002 sec.

:) optimize table summing_merge_tree_with_list_of_columns_to_sum

OPTIMIZE TABLE summing_merge_tree_with_list_of_columns_to_sum

Ok.

0 rows in set. Elapsed: 0.002 sec.

:) select * from summing_merge_tree_with_list_of_columns_to_sum

SELECT *
FROM summing_merge_tree_with_list_of_columns_to_sum

┌──────────d─┬─a─────────────┬───b─┬─x───────┬───y─┬─────────z─┐
│ 2000-01-01 │ Hello, world! │ 123 │ xxx yyy │ -23 │ 123580278 │
└────────────┴───────────────┴─────┴─────────┴─────┴───────────┘

1 rows in set. Elapsed: 0.002 sec.
```

**Comment by alexey-milovidov** [comment]
Hi.

OPTIMIZE doesn't guarantee that all data parts will be merged, it just performs additional step of selection what parts to merge and then merge them. Selection of what data parts to merge is done by some heuristic on basis of amount of data parts, their sizes and ages, non-uniformity of sizes, etc. Sometimes it could decide, that no parts should be merged right now (better to wait some time for more parts to appear, to merge them at once, to lower total cost of all merges).

For non-replicated MergeTree, OPTIMIZE selects parts to merge with modified parameters to merge heuristic, that makes selecting parts to merge more "aggressive". But for ReplicatedMergeTree, it selects parts to merge with usual parameters, exactly as it is done in background. That's why, in case of two small data parts, OPTIMIZE in ReplicatedMergeTree does nothing.

It works in same way regardless to merging method (Summing, Collapsing, etc.)

There is also special `FINAL` mode of OPTIMIZE query. Example:
```
OPTIMIZE TABLE summing_merge_tree_with_list_of_columns_to_sum PARTITION 200001 FINAL
```
In this mode, OPTIMIZE will always select all parts within specified partition and merge them.
(In exception of cases when some of that parts are already merging right now.)

Note that usually you have no need to force data to be merged. In typical scenario you always have few or even few tens of unmerged parts in your tables and all queries work regardless of number of data parts.

**Comment by remenska** [comment]
Indeed, after a while, now I see the data is summed. Thanks for the tip on optimize!
Is there any structured way to control or estimate how long before the Summing merge tree is merged, based, say, on data rate or something? It does affect our storage requirements estimations.

**Comment by alexey-milovidov** [comment]
> Is there any structured way to control or estimate how long before the Summing merge tree is merged, based, say, on data rate or something?

It is difficult to give exact number. You could expect about tens of data parts for each partition, with sizes having power law distribution. Data parts are get merged to single part only after long time (month). This is controlled in `SimpleMergeSelector.h`, `SimpleMergeSelector.cpp` (although it is not really simple).

**Comment by remenska** [comment]
Alright, thanks again. What I understand from this, is, if we want to have summed up data from SummingMergeTree to show up with a lag of about an hour (or so, controllable amount of time), we have to force-optimize.

Closing this, thanks again.

**Comment by alexey-milovidov** [comment]
To have summed data, you just have GROUP BY in all queries from SummingMergeTree.
For storage size requirement, it is also not a concern: overhead for larger datasets should be neglible.

**Comment by remenska** [comment]
Golden tip, maybe I missed it in the documentation 🥇
