### ISSUE TITLE
Undefined behavior when adding partitions in a table's directory

### ISSUE THREAD

**Issue by George3d6** [yandex/ClickHouse#1077]
I ran into some undefined behavior doing the following operations:

-> Detached some partitions and move to them another disk
-> Link back said detach partitions to the original table's directory (not in the detached dir, directly with the 'good' partitions)
-> The table logged nothing
-> Then the table "froze" in a very strange way, querying it was possible, but it wasn't querying data from the newly added softlinks. Adding data via the HTTP interface resulted in clickhouse not responding and logging nothing until curl reached a timeout.

Is the behavior of manual partition addition supposed to be UB or could this be easily fixed ? Is there another mechanism for adding partition form different directories (attach seems to be intended only for detach partitions fetch only from downloading remotely).

**Comment by alexey-milovidov** [comment]
1. You can do manual intervention to data parts only when server is not running. So, you should stop the server, then modify parts and then start the server. This is because the server maintains set of parts in memory. 

2. For Replicated tables, you cannot change set of parts, because the server will validate this set against ground truth information from ZooKeeper. If it will see unexpected parts, it will move them to "detached" directory. If you delete some parts, server will restore them from another replica.

3. You can move some parts to another volume and replace them with symlinks. But this should be done with caution. First, you need to carefully check access rights for files. Second - if server will try to move data part to another location (example - to "detached" directory), this couldn't be done if another location is in different volume. For simplicity reasons, better to move and create symlinks for entire tables, not single parts.
