### ISSUE TITLE
How many marks per table is suggested?

### ISSUE THREAD

**Issue by ramazanpolat** [yandex/ClickHouse#1126]
Taken from [Yegor Andreenko blog post ](https://medium.com/@f1yegor/clickhouse-primary-keys-2cf2a45d7324)about primary keys:

> Data structure of primary key looks like an array of marks — it’s values of primary key every index_granularity rows.

Then marks are used to skip data blocks, so that queries read much less data from the table.

Let's say I have a table with 1 billion rows. 10 million unique primary keys( 10 million different user_id in the following table). 

```
CREATE TABLE foo(
    user_id UInt64,
    event_date Date,
) ENGINE= MergeTree(event_date, (event_date), ? )

SELECT countDistinct(user_id) FROM foo;
= 10,000,000
```

In this case having 10 million marks is great since for queries involving primary key will instantly hit relevant data block. So why are we not setting index_granularity to certain value to have 10 million marks? If I have a 1 billion rows table with 10 million unique user_id, I can use 128 as index_granularity since 1B/10M = 100. 

My question is,
1- Why is 8192 recommended for index_granularity and lower values are not recommended?
2- How many marks for a table is suggested? Is 10 million to much? If it is, 10M*8 bytes = 80 MB, which is a tiny fraction in server memory.

**Comment by vavrusa** [comment]
I think it depends on your data. You're trading off memory that can be otherwise used for page cache. Also the lookup time in the sparse index isn't constant, but `log(N)` I think, so the bigger the index, the more time it takes to search it. Scanning 8191 unnecessary rows is not that expensive (when reading from disk, you'll have to read a whole block anyway) and the index can fit in memory even for tables with trillions of rows, which makes it a good default value. If you have a table with a known size and an extra memory, feel free to experiment and find out what works best for you.

**Comment by blinkov** [comment]
@ramazanpolat do you have any further questions?
