### ISSUE TITLE
a question about MergeTree engine's  tuple primary key 

### ISSUE THREAD

**Issue by wusihang** [yandex/ClickHouse#1305]
Two columns(sessionId, clientIp) are used as primary key tuple while I use MergeTree engine.  Each of primary key column can filter majority of data, then get a small set of result.  When "where clause" include sessionId, it's fast enough.  But when I try to use clientIp to filter my data, time cost is not acceptable. 
One table data volumn is approximately 1billion , and I test it on a single server with 32CPUs , 150G memory.  Do you  have any idea  about how to improve performance while using clientIp as condition ?

**Comment by KochetovNicolai** [comment]
Hi,

Primary key in ClickHouse is a sorted tuple. That's why when you use sessionId in "where clause" it's fast, but when you use only clientIp, it isn't. In the first case ClickHouse reads only data from continuous sessionId interval, but in the second it have to do many small reads for sessionIds which have appropriate clietnIp.

To improve the second case, you can either add condition with sessionId, either store duplicate data with (clientIp, sessionId) primary key.

Also, you can use other columns in primary key. Typically, it can be DateTime for session, if your queries for certain period of time. Or, you can aggregate some data for old periods, if you know what exactly you will use.

**Comment by wusihang** [comment]
Store duplicate is OK for me.  Is it possible to support multiple indexes independently?

**Comment by blinkov** [comment]
> Is it possible to support multiple indexes independently?
@wusihang at the moment the only way to do so is to keep multiple tables with same data, but different primary keys (since primary key determines how data is physically sorted in files, each table can have only one primary key)
