### ISSUE TITLE
FR: acceptable errors amount while importing out of CSV

### ISSUE THREAD

**Issue by Blasterdick** [yandex/ClickHouse#134]
It would be nice to have a flag like `--errors-allowed` while doing a command like:

`cat file.csv | clickhouse-client --database=test --query="INSERT INTO test FORMAT CSV";`

Is this possible? Thanks in advance.

**Comment by alexey-milovidov** [comment]
It is possible to add this feature.

Possible implementation: 
Add `syncAfterError` method for input formats (`IRowInputStream`).
For example, for CSV, it will skip to next line.
And then add wrapper method, that will call `read` and `syncAfterError`.

**Comment by Blasterdick** [comment]
@alexey-milovidov Nice to hear, mate. Is there any ETA on its implementation, or may be an approximate date when this feature would be included in the release? Or I'm asking for too much?)

**Comment by alexey-milovidov** [comment]
No ETA, it is not included in our plans right now.

BTW, if you are C++ developer or you have your collegues, who know C++, I may write more verbose task description.

**Comment by alexey-milovidov** [comment]
https://github.com/Civil has intention to implement this task. Here is detailed description:

1. Add virtual method
`void syncAfterError()`
to `IRowInputStream`.
By default, it throws not implemented exception.

2. Implement these methods for TabSeparated, CSV, TSKV, JSONEachRow. They will ignore bytes in ReadBuffer until next newline or eof. Use `findFirstSymbols` method, see examples of its usage.

3. Add setting `input_format_allow_errors_num` and `input_format_allow_errors_ratio`. See Settings.h.
Both are zero by default. Pass these settings to `BlockInputStreamFromRowInputStream`, see `FormatFactory`.

4. Use these settings in `BlockInputStreamFromRowInputStream`. Settings are OR-ed.
Wrap reading next row into try/catch block. Catch only exceptions that could be thrown from functions in ReadHelpers.h and from various DataTypes. If both settings are zero, then rethrow. Otherwise, increment counters and use `syncAfterError()`. Check that amount of errors is lower than at least one of thresholds.

5. Be careful to save initial exception message if `syncAfterError()` is not implemented or if errors amount is greater than threshold.

**Comment by blinkov** [comment]
This has been implemented back in 2017.

**Comment by blinkov** [comment]
This has been implemented back in 2017, see input_format_allow_errors_num and input_format_allow_errors_ratio settings.
