### ISSUE TITLE
OSX Compilation

### ISSUE THREAD

**Issue by hannesmuehleisen** [yandex/ClickHouse#141]
The bundled libpoco does not compile on OSX 10.12

Not sure whether this is something you would like to address though...

**Comment by alexey-milovidov** [comment]
It is not very easy, because no one of our developers is using Mac.

BTW, https://github.com/Civil is trying to address this issue right now, on their own initiative.

**Comment by Civil** [comment]
https://github.com/yandex/ClickHouse/pull/151 - I've made a PR request, that compiles on OS X 10.11 (don't have newer version). Though I've used gentoo-prefix as a source of packages and also used latest clang instead of xcode's one. In theory it should still be compilable with xcode's one and client most probably will work more or less. So if you want, you can try.

**Comment by alexey-milovidov** [comment]
Now it compiles and works. There still may be some difficulties, ask https://github.com/excitoon and https://github.com/Civil

**Comment by filimonov** [comment]
#235
