### ISSUE TITLE
why my clickhouse Distributed table sometime get the different result  count data at the  same conditions.

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#1443]
![image](https://user-images.githubusercontent.com/9961712/32364122-08e4a22c-c0ae-11e7-9cb4-06b40b4ab224.png)

as you see in the picture

**Comment by ztlpn** [comment]
Hi @qietingfengling !

The likely cause if the problem is that replicas of some shard do not contain the same data. So when the Distributed table chooses one or the other replica for the execution of the query the results are different. To find which shard is the problematic one, execute the query manually on every replica and check where the results are different.

Then you must find the cause of divergence. If you are using builtin ClickHouse replication, please check the `system.replication_queue` table to see if there are any problems with executing the replication queue.

If you are unable to solve the problem by yourself, please share the details of your setup (the cluster config, definitions of the Distributed table and the underlying local tables).

**Comment by qietingfengling** [comment]
Hi @ztlpn 
All of the system.replication_queue is the same result as folllow:
![image](https://user-images.githubusercontent.com/9961712/32375215-bdd9b096-c0db-11e7-8f9f-f7fad94ab361.png)

my definitions of the table as follow:
![2](https://user-images.githubusercontent.com/9961712/32376046-9a9ed19e-c0de-11e7-8f92-41cff3fe66de.jpg)

my cluster config as follow:
![3](https://user-images.githubusercontent.com/9961712/32376055-a11e3c62-c0de-11e7-941b-5eead5cfd908.jpg)

**Comment by ztlpn** [comment]
Ok, so you are not using Replicated tables (not a recommended way but understandable if you don't want the additional operational burden of a ZooKeeper cluster).

Do you insert data via the Distributed table? If yes, then you should check if there is a lot of files in the `/var/lib/clickhouse/data/shark/request/<something>/` directory. Also you should check for error log messages containing the `Distributed.DirectoryMonitor` string - if they appear, it means that there are problems with inserting to underlying tables (as Distributed table inserts are asynchronous by default, errors are visible only in the server logs).

**Comment by qietingfengling** [comment]
hi,if I set the internal_relication ture,clickhouse can use replicated tables?

yes ,I insert data via the Distributed table.

there have lot of files in the /var/lib/clickhouse/data/shark/request/<something>/ directory
the error log is as follow,if there any way to fix it

![image](https://user-images.githubusercontent.com/9961712/32423569-10407c36-c2e2-11e7-8b85-fe139d07437d.png)

**Comment by qietingfengling** [comment]
hi @ztlpn if there have a lot of files in the /var/lib/clickhouse/data/shark/request/<something>/ directory,what can I do

**Comment by ztlpn** [comment]
Can you show the stack trace that appears in the error log? The lines after `Stack Trace:`.

**Comment by wawanawna** [comment]
I see you are using IP addresses in configs. Try to use DNS names instead (from /etc/hosts), it helped me solved similar issue.

**Comment by qietingfengling** [comment]
> @qietingfengling do you have any further questions?

This happens when I use the MergeTree engine. The solution is to find a copy of the data inconsistency and replace it. Later, I used the ReplicatedMergeTree engine and I didn’t encounter it.

**Comment by itopaulojr** [comment]
> Ok, so you are not using Replicated tables (not a recommended way but understandable if you don't want the additional operational burden of a ZooKeeper cluster).
> 
> Do you insert data via the Distributed table? If yes, then you should check if there is a lot of files in the `/var/lib/clickhouse/data/shark/request/<something>/` directory. Also you should check for error log messages containing the `Distributed.DirectoryMonitor` string - if they appear, it means that there are problems with inserting to underlying tables (as Distributed table inserts are asynchronous by default, errors are visible only in the server logs).

@ztlpn  I have a question but it is not related to the issued reported.

I'm facing the following error:

`rror> monitor.table1.DirectoryMonitor: Code: 252, e.displayText() = DB::Exception: Received from clickhouse04:9000. DB::Exception: Too many partitions for single INSERT block (more than 20). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc).. Stack trace:`

I was able to reproduce it on my local environment creating 2 shards and 2 replicas, all of them with `<max_partitions_per_insert_block>20</max_partitions_per_insert_block>` config. I run an bulk insert with 40 records all of them with different partitions and got no erros but if I run a select on distributed table, I can see only 17 records and the remaining records are being blocked because 23 reach the  limit set in max_partitions_per_insert_block.

How do I stop clickhouse to try to insert this 23 remaining records?
