### ISSUE TITLE
Question: partitioning by key (worst practises from HighLoad++)

### ISSUE THREAD

**Issue by M1hacka** [yandex/ClickHouse#1513]
Hey.
Not so long ago I've visited HighLoad++ where @alexey-milovidov called splitting one table to many by key as worst practise case. He announced some built-in partitioning in ClickHouse, but I haven't found anything about it in the docs (Merge engine?). My questions are:
1) What is this built-in partitioning and how to use it?
2) I may have misunderstood how to use primary-key distributing, but in my case I have CollapsingMergeTree engine table "events" with 2 billion of records. The primary key is (id, app_id). When I make query LIKE (SELECT ... WHERE app_id=X) ClickHouse runs over all 2 billions of data (not like filtering by date index). As a result a test query with multiple joins on this table works ~30 seconds. Our main case is to do analytics inside single app only, so we decided to split it into "events_<app_id>" tables and use Merge engine table "events" in order to support multi-app queries for future. The test-query on single table now works for ~3 seconds (it has not more than 300k rows).
So, what is the best practice in this case?
Thanks.

**Comment by ztlpn** [comment]
Partitioning is built into the table engines of the MergeTree family. Traditionally tables are partitioned by the month of the date column that you supply as the first parameter in the engine definition. Starting from version 54310 you can use custom partitioning keys ([documentation in Russian](https://github.com/yandex/ClickHouse/blob/master/docs/ru/table_engines/custom_partitioning_key.md), [examples](https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00502_custom_partitioning_local.sql)).

Using the Merge engine for partitioning is suboptimal because of the static allocation of threads to tables (some threads will finish early and the corresponding cores will be underutilized) and also because some optimizations (such as transfer of WHERE clauses to PREWHERE) are turned off.

Partitioning can improve performance because min and max values of the partition key columns are stored in each table part and these values can be used to prune table parts needed for the query. But its main usage is in facilitating data manipulation tasks (such as dropping old data). To improve performance you should choose your primary key first - if the primary key is optimally used, partitioning will not improve performance. In particular if all your queries only touch the single app_id, you should put it as the first column of the primary key.

The rule of thumb for choosing the primary key: imagine the table is sorted using the primary key value. Next imagine how the set of rows that must be read to execute the query looks like. If it consists of a few wide spans, the index will be optimally used.

**Comment by M1hacka** [comment]
Thanks, I'll have a look later.
