### ISSUE TITLE
Custom Interval (Granularity) based Histogram 

### ISSUE THREAD

**Issue by adhamelia** [yandex/ClickHouse#1518]
Hi @alexey-milovidov 

I was looking to build histogram based on custom interval (granularity) using clickhouse.

I can do it based on Hourly/Daily/Yearly/Monthly using some tweaks but did not find anything build using custom interval like (5mins/6 hours/30 mins etc.)

let's say

select timestamp,avg(x) from table group by timestamp (5m/6 hours/30 mins etc...)

can you please throw some light ???

**Comment by alexey-milovidov** [comment]
If you don't mind about correct offsets of intervals in different time zones,
just round time to specified precision to GROUP BY.
Example: `intDiv(toUInt32(time), 21600) * 21600` will round to 6 hour intervals.
Otherwise do something like this: `toStartOfDay(time) + intDiv(toUInt32(toTime(time)), 21600) * 21600`.

**Comment by blinkov** [comment]
@adhamelia have you managed to use the approach described by @alexey-milovidov ?

**Comment by adhamelia** [comment]
Yeap @blinkov  .. it works superb !!! also newer version has histogram function to achieve the same thing.
