### ISSUE TITLE
Is it normal to store large strings in ClickHouse? 

### ISSUE THREAD

**Issue by shalugin** [yandex/ClickHouse#1568]
I want to use ClickHouse as storage for log data. Some log strings is pretty big (5-15 Mb).
Is it normal to store large strings (several Mb) in ClickHouse?

**Comment by theseusyang** [comment]
I think it is not suitable to store a bigger file (5-15MB), but except HDFS.

**Comment by filimonov** [comment]
Clickhouse is best in building reports by grouping and filtering data. If your data is 5-15Mb strings - it's quite hard to imagine scenarios how you can group / filter that huge strings. Proabably you need some database with full text index.

BUT: if it's possible to extract from that huge log strings some properties which are not so long and can be grouped / sorted / filetered (for example ips, useragents, etc.) - ClickHouse can be helpful for you.

**Comment by daledude** [comment]
I store some log data in Clickhouse but I don't use CH to search the MSG field. I pre-split what interests me from the MSG into fields and search on those fields. I found Elasticsearch is faster and more convenient for searching logs due to the way it parses/indexes the MSG. I just wish it had as good of compression as CH.

**Comment by blinkov** [comment]
To analyze logs with ClickHouse it is indeed recommended to parse them into individual columns before ingestion instead of storing arbitrary strings/blobs as is.

@shalugin do you have any further questions?

**Comment by shalugin** [comment]
@blinkov Thanks!
