### ISSUE TITLE
Another ReplicationMergeTree out of sync use case

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1591]
1. Create a replicated table
2. Stop the replica on one of the nodes
3. Drop one column on the other replica
4. Create a new column with the same name as the one from point 3
5. Insert some data
6. Start the node from point 2

We can observe that the node we stopped contains also the old data (before drop) while the new one only the new data.

Any way I can force the nodes to sync ? Other than dropping the entire replica on the node that was down and recreate again.

**Comment by ztlpn** [comment]
There is no other way. The reason is that ALTERs do not go through ordinary replication queue - the replicas just see the latest version of table metadata and try to convert their version to match it. So in your case the stopped replica didn't detect any change.

You can re-sync partition-by-partition though with ALTER DETACH/ATTACH.
