### ISSUE TITLE
import csv into float64 type column get wrong value 

### ISSUE THREAD

**Issue by Johnny-Three** [yandex/ClickHouse#1665]
time clickhouse-client --host=192.168.180.104 --port=9001 --query="INSERT INTO conditions FORMAT CSVWithNames" < conditions_data.csv

csv content:
  1 time,location,temperature,humidity
  2 2017-12-19 00:32:39,office,40.0000002,20.0000002
  3 2017-12-19 00:32:39,office,40.0000003,20.0000003
  4 2017-12-19 00:32:39,office,40.0000004,20.0000004
  5 2017-12-19 00:32:39,office,40.0000005,20.0000005
  6 2017-12-19 00:32:39,office,40.0000006,20.0000006
  7 2017-12-19 00:32:39,office,40.0000007,20.0000007
  8 2017-12-19 00:32:39,office,40.0000008,20.0000008
  9 2017-12-19 00:32:39,office,40.0000009,20.0000009
 10 2017-12-19 00:32:39,office,40.000001,20.000001
 11 2017-12-19 00:32:39,office,40.0000011,20.0000011
 12 2017-12-19 00:32:39,office,40.0000012,20.0000012
 13 2017-12-19 00:32:39,office,40.0000013,20.0000013

:) select * from conditions;

SELECT *
FROM conditions 

┌────────────────time─┬─location─┬─temperature─┬───────────humidity─┐
│ 2017-12-19 00:32:39 │ office   │  40.0000002 │         20.0000002 │
│ 2017-12-19 00:32:39 │ office   │  40.0000003 │         20.0000003 │
│ 2017-12-19 00:32:39 │ office   │  40.0000004 │         20.0000004 │
│ 2017-12-19 00:32:39 │ office   │  40.0000005 │         20.0000005 │
│ 2017-12-19 00:32:39 │ office   │  40.0000006 │         20.0000006 │
│ 2017-12-19 00:32:39 │ office   │  40.0000007 │         20.0000007 │
│ 2017-12-19 00:32:39 │ office   │  40.0000008 │         20.0000008 │
│ 2017-12-19 00:32:39 │ office   │  40.0000009 │         20.0000009 │
│ 2017-12-19 00:32:39 │ office   │   40.000001 │          20.000001 │
│ 2017-12-19 00:32:39 │ office   │  40.0000011 │ 20.000001100000002 │
│ 2017-12-19 00:32:39 │ office   │  40.0000012 │         20.0000012 │
│ 2017-12-19 00:32:39 │ office   │  40.0000013 │         20.0000013 │
└─────────────────────┴──────────┴─────────────┴────────────────────┘

12 rows in set. Elapsed: 0.002 sec. 

pay attention to the value  20.000001100000002 here . It's a wrong value that doesn't appears in the csv file .

**Comment by KochetovNicolai** [comment]
It's expected behavior. ClickHouse use fast and not very precise parser.
More precisely, string `'20.0000011'` is parsed as `20 + 0.000001 + 0.000001 = 20.000001 + 0.0000001 = 20.000001100000002` for float64.

**Comment by silviucpp** [comment]
@KochetovNicolai probably it;s better ti implement as well and accurate parser even if it's slower and users can enable it from config

**Comment by filimonov** [comment]
That works weird:
```sql
:) select toFloat64(20 + 0.000001 + 0.0000001) x;
┌──────────────────x─┐
│ 20.000001100000002 │
└────────────────────┘

:) select toFloat64( 0.000001 + 0.0000001 + 20) x;
┌──────────x─┐
│ 20.0000011 │
└────────────┘

:) select toFloat64(20.0000011) x;
┌──────────x─┐
│ 20.0000011 │
└────────────┘
```

**Comment by alexey-milovidov** [comment]
@filimonov That's totally correct and does not related to rough parsing.

Example:
```
$ python
Python 2.7.13 (default, Nov 23 2017, 15:37:09) 
[GCC 6.3.0 20170406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 20 + 0.000001 + 0.0000001
20.000001100000002
```

```
 nodejs
> 20 + 0.000001 + 0.0000001
20.000001100000002
```

In contrast:

```
$ perl -e 'print((20 + 0.000001 + 0.0000001) . "\n")'
20.0000011
```

```
$ php -r 'echo((20 + 0.000001 + 0.0000001) . "\n");'
20.0000011
```

Actually the result of calculation is the same, but the text printed is depending on how the floating point numbers are formatted.

**Comment by filimonov** [comment]
Yep. I know about that innacuracy of floats, just was surprised that float summing is not associative (changing order of summing 3 elementsin that case you get different result). 

May be by adjusting a bit of floats formatting (like in php / perl / go) can make everybody happy. (may be switched by option).

**Comment by alexey-milovidov** [comment]
> May be some adjusting of floats formatting (like in php / perl / go) can make everybody happy.

These are different decisions. As I understand, 
in first variant, numbers are formatted in a way, that can be parsed back to the same bit representation,
in second variant, numbers are formatted with precision up to fixed number of digits.

First variant gives you roundtrip property - you can get table dump and load it back without loss of precision.

(Assuming, numbers are parsed to the nearest machine-representable number, which is not true in ClickHouse. In ClickHouse, floating point parsing not necessarily gives you the closest machine-representable number.)

In this case, `20 + 0.000001 + 0.0000001` != `20.0000011` (bit exactly).

PS. https://randomascii.wordpress.com/2012/03/08/float-precisionfrom-zero-to-100-digits-2/

**Comment by alexey-milovidov** [comment]
We may implement a function to format floats with specified rules, and a setting with default float formatting.

**Comment by filimonov** [comment]
I like using printf / sprintf in any language i code, so if some kind of sprintf can be adopted in clickhouse - it woukd be really cool.

**Comment by cyfdecyf** [comment]
I'm also affected by the float parsing precision problem. I am trying to hack `readFloatTextImpl` in `ReadHelpers.h` to work around the problem for now.

**Comment by cyfdecyf** [comment]
I made a dirty hack to import float64 precisely. This works for me as a temporary workaround for now.

**Comment by filimonov** [comment]
@cyfdecyf can you check what a performance downgrade is?

**Comment by cyfdecyf** [comment]
@filimonov Just done a simple performance test, import time is a little more than doubled.

Test data is a two columns (date and double) CSV with 10,000,000 rows, 279MB on disk.

```python
import numpy as np
import pandas as pd

df = pd.DataFrame()
df['v'] = np.random.uniform(size=10000000) * 1000
df['dt'] = '2018-01-11'
df[['dt','v']].to_csv('data.csv', index=False, header=False)
```

Test script:

```bash
clickhouse-client --query="CREATE DATABASE IF NOT EXISTS perf"
clickhouse-client --query="DROP TABLE IF EXISTS perf.test"
clickhouse-client --query="CREATE TABLE perf.test (dt Date, v Float64) ENGINE = MergeTree PARTITION BY dt ORDER BY dt"
/usr/bin/time clickhouse-client --query="INSERT INTO perf.test FORMAT CSV" <data.csv
```

Import time increased from 1.16 seconds to 7.95 seconds with commit cyfdecyf/ClickHouse@632dcf1, on an Intel Xeon Gold 2.3GHz CPU.

The slow down mainly comes from ``ostringstream``, after switch to a plain char array as in commit cyfdecyf/ClickHouse@a38bce6, import time is 2.62 seconds. I also tried `sscanf` to parse float, which is slower than `std::stod` and import time is 3.62 seconds.

**Comment by alexey-milovidov** [comment]
There is `StringToDoubleConverter` in `double-conversion` library.
I think it's the only possible choice.

**Comment by alexey-milovidov** [comment]
I've implemented correct parsing of floats: https://github.com/yandex/ClickHouse/compare/correct-parse-floats?expand=1

Added peformance test: `dbms/tests/performance/float_parsing/float_parsing.xml` for various cases.
In extreme case, it have 1.6 times performance decrease (when parsing integer numbers as floats).

(How to run: in the directory with file, type `clickhouse performance-test .`)

Now it's unclear, is it worth to merge.

@cyfdecyf Could you please apply your own test for my branch?

**Comment by cyfdecyf** [comment]
@alexey-milovidov I get following error message when running my own performance test mentioned above:

```
Code: 72. DB::Exception: Cannot read floating point value: (at row 1)

Row 1:
Column 0,   name: dt, type: Date,    parsed text: "2018-01-11"
Column 1,   name: v,  type: Float64, ERROR: text "171.721937" is not like Float64
```

**Comment by cyfdecyf** [comment]
@alexey-milovidov I've tested with the latest commit in your branch, by changing `readFloatText` to use `readFloatTextPrecise`, my application are getting expected results.

My simple performance test reduced to only 0.8 seconds when using `readFloatTextFast`, just half of the origin float parsing implementation, `readFloatTextPrecise` uses 1.5 seconds which is the same as origin.

The performance of `readFloatTextFast` is great as it's both faster and more accurate then before. But as a user, I would suggest use `readFloatTextPrecise` as the default implementation.

Precision problem is difficult to find out and may just be ignored. I found the problem because my application results differs when using ClickHouse compared to my original data source. I didn't find any note on in-precise float parsing in ClickHouse document and it took me some time to identify the root cause. If this is a new application and ClickHouse is the only data source, I may not notice this problem in a short time.

**Comment by alexey-milovidov** [comment]
Thank you!

It's still difficult to decide what is better. I'm really in doubt.

Probably I can make `readFloatTextFast` function to give exact result for all machine-generated inputs (inputs that was formatted with sprintf, double conversion, etc.), but with sacrifice 1..2 bits of precision for some unusual user inputs.

There are many cases when we want to prefer faster parsing. Example is importing monitoring/sensor data - it's quite common use case for ClickHouse (though in this use case it's much better to avoid text formats). ClickHouse in it's design principles always prefer faster methods by default, even when it leads to some compromise.

There are arguments that sacrificing precision is Ok:

1. You anyway will get same lost of precision when doing almost any operation.

2. You don't get one-to-one binary to text correspondence, because there are many NaNs that are represented by different bits, and all of them are formatted either as `nan` or `-nan`.

3. Loss of precision when converting to text and back is "idempotent". You will not get any additional loss in precision if you convert to text and back many times.

4. Sources for numbers (sensors) often have much less precision comparable to what amount of precision you lose when parsing.

5. If you parse numbers in perfect way (to the closest machine representable number) you get theoretical loss of precision anyway (comparable to real or decimal number), and one bit difference (example: number, that is next closest machine representable number, or closest from the other side of real number) is the same in nature. It's more reasonable to talk that you need "canonical" way of parsing numbers.

**Comment by cyfdecyf** [comment]
@alexey-milovidov Thanks for your explanation. Great points and I agree differ in 1 bit won't be a problem for most applications. I'll check my application results with `readFloatTextFast` tomorrow.

If you choose the faster way by default, just make sure to mention the problem in document, and better to give user an option to choose the "canonical" way.

**Comment by cyfdecyf** [comment]
@alexey-milovidov My application result differs using `readFloatTextFast` compared to `readFloatTextPrecise`, but only just a few places with a 1e-4 difference. The difference is much less compared to master branch.

**Comment by miggi** [comment]
Hi @cyfdecyf 
**" DB::Exception: Cannot read floating point value: (at row 1)"** we're still getting the errors when inserting large "flat" column set. Actually we've broke our production after upgrade and related issue. How to overcome this problem ?

We use jdbc-clickouse batching and it's hard to figure out what's the actual problem (in what column) here ? On old CH distribution all works fine.. 

Thanks for help!

**Comment by alexey-milovidov** [comment]
Can you give us one or a few rows for an example?

How to do it:
- find out a batch that you cannot insert;
- save it somewhere; check that the issue still reproduce, when you try to insert it again;
- leave just one row where the issue still reproduce.

**Comment by cyfdecyf** [comment]
@miggi I use clickhouse-client to import CSV which works fine. Maybe the problem only shows up in jdbc related code.

**Comment by miggi** [comment]
Alright guys, so the problem was in incorrect mapping, String value was trying to be saved to Float64 schema.This was silently ignored in previous releases, but current version is throwing error. 

Anyway, I see no issue here, so thanks for quick support. Cheers!

**Comment by Axelfoley85** [comment]
Still got the same issue on clickhouse 19.15.3.6 when importing TabSeparated data. How can I turn on readFloatTextPrecise?

```
cat /tmp/dump.txt
1560038400	3600	12139	12369	foo	15	bar	12345	1236	3.397	\N

cat /tmp/dump.txt | clickhouse-client -q "insert into tmp.testTable format TabSeparated"

clickhouse-client -q "select * from tmp.testTable"
1560038400	3600	12139	12369	foo	15	bar	12345	1236	3.3970000000000002	\N

```
