### ISSUE TITLE
Kafka Engine drops messages

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#1690]
@vavrusa 

This is using the same test setup as #1625 but the topic only has one partition with replication factor of 2

Generating 500k messages I've noticed that KafkaEngine will drop some messages
Across the 500k messages about 80-90 messages are missing from the materialised view.

This seems to happen in clusters where 5-10 messages are missing and then it continues with the new messages.

I've verified that the missing messages exist in the kafka topic

**Comment by vavrusa** [comment]
Can you start clickhouse with debug logging and post logs?

It might lose messages if a rebalance happens and flushing of the last block doesn't finish within the session timeout.

**Comment by vavrusa** [comment]
So I tried to reproduce your setup and there are a couple things going on:

1. The producer script doesn't produce (or flush) all messages, I'm noticing a few messages missing when I read them with kafkacat

```
$ kafkacat -b localhost:9092 -G test_group_7 test_ck > out; wc -l out
% Group test_group_7 rebalanced (memberid rdkafka-11a72d47-b0ab-416d-a461-a25524873c98): assigned: test_ck [0], test_ck [1]
% Reached end of topic test_ck [0] at offset 350636
% Reached end of topic test_ck [1] at offset 349048
^C% Group test_group_7 rebalanced (memberid rdkafka-11a72d47-b0ab-416d-a461-a25524873c98): revoked: test_ck [0], test_ck [1]
   99939 out
```

I switched producer to replay a file with kafkacat instead and now getting all messages:

```
$ python test_producer.py -n | wc -l
   99999
$ python test_producer.py -n | kafkacat -b localhost:9092 -t test_ck -p -1
% Auto-selecting Producer mode (use -P or -C to override)
$ kafkacat -b localhost:9092 -G test_group_7 test_ck > out; wc -l out
% Group test_group_7 rebalanced (memberid rdkafka-f048552c-e084-4e51-bdae-3d6c57321bf9): assigned: test_ck [0], test_ck [1]
% Reached end of topic test_ck [0] at offset 400555
% Reached end of topic test_ck [1] at offset 399128
^C% Group test_group_7 rebalanced (memberid rdkafka-f048552c-e084-4e51-bdae-3d6c57321bf9): revoked: test_ck [0], test_ck [1]
   99999 out
```

So now I should be able to verify this with Kafka client in CH:

```
:) select count() from test_kafka_ck

SELECT count()
FROM test_kafka_ck

┌─count()─┐
│   99999 │
└─────────┘

1 rows in set. Elapsed: 2.548 sec. Processed 100.00 thousand rows, 2.00 MB (39.25 thousand rows/s., 785.02 KB/s.)
```

There was one problem that probably didn't affect you (offsets committed twice in a sequence), and one with materialized views using maximum block size > 1 (which caused it to read extra messages, but not use them in some cases like LIMIT or time limit or insert block size reached). When I produce messages to the topic and create MV, it has all the messages:

```
:) CREATE MATERIALIZED VIEW test_kafka_ck_mat ENGINE = MergeTree(day, (day, key), 8192) AS SELECT toDate(toDateTime(timestamp)) AS day, key, xxx from test_kafka_ck

CREATE MATERIALIZED VIEW test_kafka_ck_mat
ENGINE = MergeTree(day, (day, key), 8192) AS
SELECT
    toDate(toDateTime(timestamp)) AS day,
    key,
    xxx
FROM test_kafka_ck

Ok.

0 rows in set. Elapsed: 0.005 sec.

:) select count() from test_kafka_ck_mat

SELECT count()
FROM test_kafka_ck_mat

┌─count()─┐
│   99999 │
└─────────┘

1 rows in set. Elapsed: 0.003 sec. Processed 100.00 thousand rows, 200.00 KB (29.66 million rows/s., 59.33 MB/s.)
```

When I drop the data and produce more messages, it will however read 1 message less, but from the logs it seems like CH got it but it wasn't used, probably because of how time based limit works.

```
:) alter table `.inner.test_kafka_ck_mat` drop partition '203805'

0 rows in set. Elapsed: 0.005 sec.

:) select count() from test_kafka_ck_mat

SELECT count()
FROM test_kafka_ck_mat

┌─count()─┐
│   99998 │
└─────────┘

1 rows in set. Elapsed: 0.003 sec. Processed 100.00 thousand rows, 200.00 KB (29.66 million rows/s., 59.33 MB/s.)
```

Can you confirm this makes sense?

**Comment by vavrusa** [comment]
I patched the IProfilingInputStream to check limits before pulling block from the stream, this should fix the last message missing.

**Comment by tobad357** [comment]
@vavrusa will try to build an test with the new changes
Re the flush, I had added that to the local test but forgot to  update the code in the example I added to the previous issue. I did however verify that the messages were in the topic with kafka cat but not in clickhouse

I will revert once I've worked out how to build :)

**Comment by tobad357** [comment]
Tested on a new build and seems to work as expected now
No dropped messages
