### ISSUE TITLE
[Question] CollapsingMergeTree or ReplacingMergeTree's performance

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1754]
Engine: CollapsingMergeTree or ReplacingMergeTree
when use GROUP BY / FINAL keywords etc , how is the performance?

**Comment by ztlpn** [comment]
In general you can expect performance of queries with FINAL to be significantly worse than ordinary queries, because they are executed in the single thread. By contrast GROUP BY statements are executed in parallel (that doesn't depend on which MergeTree engine is used). Note that you can emulate FINAL to the extent with a GROUP BY and the `argMax()` function.
