### ISSUE TITLE
Code: 49. DB::Exception: Unexpected value 0 for type Enum16

### ISSUE THREAD

**Issue by Tgarifullin** [yandex/ClickHouse#184]
When I'm trying to make select with totals grouping by Enum16 field, I've got an error:
`Code: 49. DB::Exception: Unexpected value 0 for type Enum16('value1' = 1, 'value2' = 2, ... 'value69' = 69)
`

Problem query:
`SELECT event_name, count() c FROM event GROUP BY event_name WITH TOTALS;
`

Slightly different query works fine:
`SELECT toInt16(event_name) e, count() c FROM event GROUP BY e WITH TOTALS;
`

**Comment by alexey-milovidov** [comment]
Confirmed. WITH TOTALS tries to generate a value with zero, not default value for enum. This is a bug.

**Comment by alexey-milovidov** [comment]
Fixed in
6d914bc4db55cae789bf88e8e689b9fd7aa80a57 
643c2b747a9512b43355c314185497fa3114e8c4

But there is also the same issues with
- JOIN;
- array subscript and arrayFirst functions in case of missing element;
- parsing of JSONEachRow and TSKV format in case of missing Enum field.
when Enum data type doesn't have zero.
