### ISSUE TITLE
[Question] insert data via the distributed table or local table

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1854]
hi, distributed table based on local table. when insert data, one way is to write data to distributed table,
the another is to write data to local table on nodes. 
#### question
if create distributed table use shard key, but insert data via local table, when query the distributed table using shard key, will it impact results? 

official document says:
```
You should be concerned about the sharding scheme in the following cases:
- Queries are used that require joining data (IN or JOIN) by a specific key. If data is sharded by this key, you can use local IN or JOIN instead of GLOBAL IN or GLOBAL JOIN, which is much more efficient.
```

**Comment by alexey-milovidov** [comment]
Sharding key in Distributed table is used only at INSERT.
For SELECTs, sharding key does not make sense and Distributed tables always query all shards.

Insertion to local tables is more efficient and more flexible than insertion to Distributed table.
It is more efficient because it avoids excessive copying of temporary data.
It is more flexible because you can use any sophisticated sharding schemas, not only simple sharding by modulo of division.

Insertion to local tables require more logic on your client application and can be more difficult to use. But also it is conceptually more simple.

If your queries rely on some assumptions on data distribution, like queries that use IN or JOIN (joining co-located data) instead of GLOBAL IN, GLOBAL JOIN, then you have to maintain correctness by yourself.
