### ISSUE TITLE
DISTINCT is significantly slower than corresponding GROUP BY query

### ISSUE THREAD

**Issue by vozbu** [yandex/ClickHouse#199]
Seems illogical that query that returns more data is executed faster:

```
> clickhouse-client -m
ClickHouse client version 1.1.54046.
Connecting to localhost:19000.
Connected to ClickHouse server version 1.1.54046.

:) SELECT ev_type, count() FROM events GROUP BY ev_type;

SELECT 
    ev_type, 
    count()
FROM events 
GROUP BY ev_type

┌─ev_type─┬────count()─┐
│       0 │ 1361463625 │
│       1 │    4366468 │
│      10 │  432952206 │
└─────────┴────────────┘

3 rows in set. Elapsed: 1.318 sec. Processed 1.80 billion rows, 1.80 GB (1.36 billion rows/s., 1.36 GB/s.) 

:) SELECT DISTINCT ev_type FROM events;

SELECT DISTINCT ev_type
FROM events 

┌─ev_type─┐
│       0 │
│       1 │
│      10 │
└─────────┘

3 rows in set. Elapsed: 5.819 sec. Processed 1.80 billion rows, 1.80 GB (309.14 million rows/s., 309.14 MB/s.) 

:) Bye.
```

**Comment by alexey-milovidov** [comment]
Implementation of DISTINCT is somewhat distinct than GROUP BY.

1. For GROUP BY, we implemented many specializations for different combinations of types of columns to GROUP BY, but for DISTINCT, only generic implementation is used. This is fixable.

2. Query with DISTINCT could return result as soon as next block of data is get filtered, but for GROUP BY, we must wait for whole result to be ready. This is also fixable, because if query with GROUP BY does not have aggregate functions, it could also return data sooner.

We definitely should make DISTINCT faster.

**Comment by artpaul** [comment]
We have optimized execution of DISTINCT in https://github.com/yandex/ClickHouse/commit/d1383c5f62d8251d8e01c8a106847b6dfea317a0 . On our closed test-set we gained execution time closed to GROUP BY. But in some cases DISTINCT is still slower than GROUP BY. We will investigate and optimize it.
