### ISSUE TITLE
FORMAT RowBinary, 3 bytes per short record

### ISSUE THREAD

**Issue by mephistopheies** [yandex/ClickHouse#2091]
I dumped column which contains only -1, 0 and 1 values to the binary file like this
```
clickhouse-client --max_threads="16" --query="select if(is_attributed is null, -1, is_attributed) from talkingdata.raw where click_id in (-44004074, -180452059, 2890381) FORMAT RowBinary"  > ./tmp.bin
```

then I read it with python, I was expecting 1 byte per record for signed byte or 2 bytes for short, but actually I have 3 there first one is always 0

```
f = open('tmp.bin', 'rb')
print(struct.unpack('b', f.read(1)))
print(struct.unpack('h', f.read(2)))
>(0,)
>(-1,)

print(struct.unpack('b', f.read(1)))
print(struct.unpack('h', f.read(2)))
>(0,)
>(0,)

print(struct.unpack('b', f.read(1)))
print(struct.unpack('h', f.read(2)))
>(0,)
>(1,)
```

may be I'm doing something wrong in python, but with other types I don't have such issues; for example I have a column with values from 10 to 30 and it is dumped as 1 bytes per record and `struct.unpack('b', f.read(2))` reads it correctly, same with int with 4 per record

**Comment by alexey-milovidov** [comment]
The reason is that `if(is_attributed is null, -1, is_attributed)` has Nullable type.
You can check it with `toTypeName(if(is_attributed is null, -1, is_attributed))`.

You can replace it with `coalesce(is_attributed, -1)` to get non-Nullable type.

The first byte in binary representation of Nullable is "is NULL" flag, which is zero in your case.

**Comment by mephistopheies** [comment]
thanks!
