### ISSUE TITLE
Support arbitrary data type for ranges in 'range_hashed' dictionary

### ISSUE THREAD

**Issue by alex-zaitsev** [yandex/ClickHouse#2093]
'range_hashed' dictionary supports only Date for range min/max. 

Please consider support for other datatypes, e.g. DateTime, IntXX.

    <range_min>
        <name>smth_from</name>
        <type>Int32</type>
    </range_min>

    <range_max>
         <name>smth_to</name>
         <type>Int32</type>
    </range_max>

**Comment by k4otix** [comment]
This would be great. My use case is doing range queries for IP addresses but I cannot use `ip_trie` since many of the ranges cannot be represented as CIDR blocks, so I would want to use the FixedString(16) representation resulting from `IPv6StringToNum()`. 

However, it would be nice for any ordered type to be able to be used for range_min/range_max

**Comment by vpanfilov** [comment]
It would be great for determining region from telephone number.
