### ISSUE TITLE
Failed to cast proper arrays

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2111]
Hello,

The following cast is failing even if it shouldn't:

```sql
select CAST([-9223372036854775808, 9223372036854775807] AS Array(Nullable(Int64)))

Code: 386, e.displayText() = DB::Exception: There is no supertype for types Int8, UInt64 because some of them are signed 
integers and some are unsigned integers, but there is no signed integer type, 
that can exactly represent all required unsigned integer values, e.what() = DB::Exception

select CAST([-1, 9223372036854775807] AS Array(Nullable(Int64)))

Code: 386, e.displayText() = DB::Exception: There is no supertype for types Int64, UInt64 because some of them are signed
integers and some are unsigned integers, but there is no signed integer type, that can exactly represent all required
unsigned integer values, e.what() = DB::Exception

select CAST([0, 9223372036854775807] AS Array(Nullable(Int64)))

It's OK
```
Int64 stores value from: –9223372036854775808 to 9223372036854775807 so all 3 casts should work.

Silviu

**Comment by silviucpp** [comment]
@alexey-milovidov any input on this bug ?

**Comment by alexey-milovidov** [comment]
The behaviour is determined by types of arguments, regardless to values of constants.

Neither
`SELECT [-9223372036854775808, 9223372036854775807]` 
`SELECT [toInt64(0), toUInt64(0)]`
`SELECT [number, -number] FROM numbers(10)`
work by the same reason.

**Comment by silviucpp** [comment]
OK I thought best approach is to try to find the data type that fit's the values or in case of a cast to use the data type from the cast.

**Comment by alexey-milovidov** [comment]
We have two functions:
- creation of array;
- CAST.

These functions are executed independently.
The issue is related just to creation of array.

**Comment by silviucpp** [comment]
But creation of the array shouldn't somehow find the best interval that can fit all the values ?
Don't you think this will be the best approach ?

Silviu

**Comment by alexey-milovidov** [comment]
> Don't you think this will be the best approach?

Not quite, because it will break some other expectations.

Array, internally, can be created in two ways:
1. Simple way, where it's an array of literals: `[1, 2, 3]`.
2. Complex way, where it's an array of more complex expressions: `[1 + 2, 3]`.

In the first case, it is parsed as single literal (`Field`). Then type is determined in `FieldToDataType.cpp`.
In the second case, it is parsed as `array` function with array elements as an arguments.

Now lets look at the second case (`array` function).

The type of function result is usually determined only by types of its arguments, not by values of arguments (regardless of whether arguments are constants or not).

There are some exceptions like `toFixedString('abc', 5)` and `tupleElement(('a', 123), 1)`, but these exceptions exist only for cases when some argument is always constant.

If we will let the type of array to be dependent on values of constants, we will get inconsistent result in cases:

`SELECT toTypeName([-1, 1])`
and
`SELECT toTypeName([-a, a]) FROM (SELECT max(number) FROM numbers(1))`

Now lets look at the first case (array literal).

The type of array literal is determined in `FieldToDataType.cpp`.
We simply get the supertype from all elements of the array, regardless to it's values.
Why we cannot analyze values of elements and choose more appropriate data type?

Because this case (parsing of array literal as a whole without call to `array` function) is just an optimization for the second case.

Optimization should not change the semantics.
Otherwise we will get inconsistent results for cases:

`SELECT toTypeName([-1, 1])`
and
`SELECT toTypeName([-1+0, 1])`

**Comment by alexey-milovidov** [comment]
```select CAST([toInt64(-9223372036854775808), toInt64(9223372036854775807)] AS Array(Nullable(Int64)))```
