### ISSUE TITLE
Wrong results when comparing Float32 numbers (Float64 works as expected)

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2112]
Hello,

Having the following table and values:

```sql
CREATE TABLE test_floats(f32 Float32, f64 Float64) ENGINE = Memory;
INSERT INTO test_floats(f32, f64) values (10.2, 10.2);
INSERT INTO test_floats(f32, f64) values (32.4, 32.4);
```

If you run the following queries:

```sql
SELECT * FROM test_floats; 

Shows correct values for both;

SELECT count(*) FROM test_floats where f32 = 10.2;

returns 0

SELECT count(*) FROM test_floats where f64 = 10.2;

return 1 
```

Same comparing using 32.4 .

This was even poor in the past where even Float64 was not working but was improved in some recent commits in clickhouse but still seems that this case is not working..

**Comment by filimonov** [comment]
The reason is that for floats which appear in query ClickHouse uses Float64 by default. 
```
:) select toTypeName(10.2);
┌─toTypeName(10.2)─┐
│ Float64          │
└──────────────────┘
```

So 10.2 in Float64 from query exactly (binary) equal to 10.2 in Float64 in table. 

But for 10.2 (in Float64) != 10.2 (in Float32).
```
:) select toFloat64(10.2) = toFloat32(10.2);
┌─equals(toFloat64(10.2), toFloat32(10.2))─┐
│                                        0 │
└──────────────────────────────────────────┘
1 rows in set. Elapsed: 37.863235ms
```

Generally - you should not compare floats directly, in java for example it will give a warning "JAVA0078 Floating point values compared with ==". Safe way is using something like: 
```java
float epsilon = Float.MIN_NORMAL;  
if(Math.abs(float2 - float1) < epsilon){...}
```

Choosing correct epsilon - actually depends on context, and default choice is "difference between 1.0 and the next value representable by the floating-point type".  (see http://en.cppreference.com/w/cpp/types/numeric_limits/epsilon )

**Comment by silviucpp** [comment]
@filimonov  I  know that comparing floats is not accurate but I'm expecting to work at least on the same limitations c++ has. Here problem I'm sure is not because of the way real numbers are represented and most probably is a bug in clickhouse somewhere.

**Comment by filimonov** [comment]
But may be ClickHouse can implement `almost_equal` function (with machine epsilon) for floats.

For general usage it's not always nice to use such approximations, as they are not so cpu-efficient, and also can have some undesired side effects, one of them - loose transitive property. So if 
almost_equal(a,b) and almost_equal(b,c) then almost_equal(a,c) can be false.

For example if epsilon is 0.01. 
1.00 is almost equal to 1.01, and 1.01 is almost equal to 1.02, but 1.00 is not almost equal to 1.02.

**Comment by filimonov** [comment]
@silviucpp but in pure c++ there is the same limitation. 
Please try: http://cpp.sh/2yjdn

**Comment by silviucpp** [comment]
@filimonov yes it's a but in clickhouse that when you do this filtering : `f32 = 10.2`, 10.2 is casted to `Float64` and not to the type of `f32`. At least this is my opinion that as you also spotted the proper cast is not triggering the bug.

**Comment by filimonov** [comment]
But if you really need to do binary comparison, you can always force typecast, so if you want to look for exact Float32 value you can use something like ```WHERE f32 = toFloat32(10.2)```.

But still in most cases it's a vary bad idea, as in some cases even same float can have multiple machine representation, which will not be equal to each other.

Floats are for some approximate stuff, for accurate/financial calculations usually DECIMAL types are used in DBMSs. Clickhouse does not support Decimals (yet, see #2021).

**Comment by alexey-milovidov** [comment]
Although we can cast both sides to Float32 when comparing Float32 with Float64,
it will introduce another troubles, because:

1. It will differ from the behaviour of C++ (now it is consistent).
2. Some results will be wrong, for example:
```
SELECT CAST(inf AS Float32) = 1e100
```
now it returns 0 as expected.
If we will cast both sides to Float32 before comparison, it will return 1.
