### ISSUE TITLE
FREEZE PARTITION not working properly with custom partitions.

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2478]
```sql
CREATE TABLE my_project.my_collection_1_src (
  timestamp DateTime,  
  username Nullable(String),  
  user_id Nullable(UInt64),  
  register_ts Nullable(UInt64),  
  is_vip Nullable(UInt8)) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY timestamp SETTINGS index_granularity = 8192
```

Insert some data:

```sql
INSERT INTO my_project.my_collection_1(timestamp, username, user_id, register_ts, is_vip) values(toDateTime('2001-01-01 00:00:00'), 'jon', 1, 100, 0);
```

A part called `200101_4_4_0` is created.

Running:

```sql
ALTER TABLE my_project.my_collection_1_src FREEZE PARTITION '200101_4_4_0';
```

Returns

```sh
Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section. Expected: UInt32. Got: String, e.what() = DB::Exception
```

In order to work I need to run:

```sql
ALTER TABLE my_project.my_collection_1_src FREEZE PARTITION 200101;
```

This is an undocumented behavior at least in case you don't consider it bug. Also this add limitations because you can backup only using prefix not a part by it's full name.

**Comment by silviucpp** [comment]
@alex-zaitsev you are right. I consulted the documentation again and seems you cannot FREEZE only specific parts. 

But 2 bugs still remains here:

1. The one you mentioned : FREEZE PARTITION '200101', it should work both in single quotas and without
2. Documentation doesn't say anything regarding WITH NAME syntax which pretty powerful. You need to read the code in order to realize that this feature exists.

**Comment by silviucpp** [comment]
Also in documentation :

Creates a local backup of one or multiple partitions. The name can be the full name of the partition (for example, 201403), or its prefix (for example, 2014) - then the backup will be created for all the corresponding partitions.

My data folder looks like:

200101_4_4_0
200101_6_6_0
201806_1_5_2

I tried to use : 

ALTER TABLE my_project.my_collection_1_src FREEZE PARTITION 2; 

and nothing is generated. But If I use the full name 200101 or 201806 it's working. Based on documentation also only 2 should work. I'll say this is the third bug. BTW using traditional partition method it's working fine

**Comment by ztlpn** [comment]
```sql
ALTER TABLE my_project.my_collection_1_src FREEZE PARTITION '200101_4_4_0';
```
won't work because `'200101_4_4_0'` is a part, not a partition (each partition consists of several parts with the same value of the partition key).

Next, because in your case the partition key is integer-valued, you can't use strings to specify partitions - the parser is more strict. Also, for custom partitioning there is a separate concept called the partition ID - a string that is used for directory names and such. It is distinct from the partition key value (which can be any ClickHouse value) but for integer partition keys it coincides with the string representation of the integer. So for custom-partitioned tables you can use `FREEZE PARTITION 2001` or `FREEZE PARTITION ID '2001'` - they are equivalent.

Finally the prefix matching doesn't work for custom-partitioned tables because it can introduce ambiguity: suppose your tables are partitioned by some integer partition key and you have partitions `1` and `11`. With prefix matching you just won't be able to select only partition `1` for freezing. Of course, ideally there should be some mechanism to specify several partitions at once (something like `FREEZE PARTITION WHERE expr` but this feature is not yet well thought-out.

These differences are stated in [the custom partitioning key docs](https://clickhouse.yandex/docs/en/table_engines/custom_partitioning_key/):
> Note: For old-style tables, the partition can be specified either as a number 201710 or a string '201710'. The syntax for the new style of tables is stricter with types (similar to the parser for the VALUES input format). In addition, ALTER TABLE FREEZE PARTITION uses exact match for new-style tables (not prefix match).

The differences should also be clearly stated in [the docs for ALTER PARTITION statements](https://clickhouse.yandex/docs/en/query_language/queries/#manipulations-with-partitions-and-parts) and I've created a task for our documentation team to do that.

**Comment by silviucpp** [comment]
You can close the bug as time documentation will be updated to reflect this.
Also when I checked docs few weeks ago there was no mention for WITH NAME  which is a nice feature. 

Thanks
Silviu
