### ISSUE TITLE
High latency when importing stream from kafka

### ISSUE THREAD

**Issue by elprup** [yandex/ClickHouse#2508]
After created queue kafka table, target table and consume material view, [clickhouse kafka docs](https://clickhouse.yandex/docs/en/table_engines/kafka/),  Kafka data is imported but with high latency(around 15minutes).
Refer to former issue, lower max_block_size will solve the problem #2169. But indeed the throughput changes and low latency is always necessary.

stream_flush_interval_ms seems to be the right config to handle that but as I noticed it only works when topic does not receive any message for sometime. If you continue push messages into source kafka topic, the timer will not work.

Source kafka Throughput is low (100 messages/sec).
stream_flush_interval_ms, max_block_size remains default.

So how to flush to materialize view every N seconds whenever the max_block_size is reached?

**Comment by shangshujie365** [comment]
I have the same problem, stream_flush_interval_ms can't work

**Comment by teunhoogendoorn** [comment]
Same problem here:

With a dynamic throughput (for example 10.000 messages/sec during the day and 100 messages/sec during the night) it is hard to determine correct values for max_insert_block_size and stream_flush_interval_ms to import data into ClickHouse with a predictable delay.  So something like the suggested "flush every N seconds" would be great.

Thanks!

**Comment by TH-HA** [comment]
May be putting a Buffer between Kafka and your target can solve your issue. 
Buffer engine allow to specify min/max time,rows and size before flushing to the target. 

Regards

**Comment by filimonov** [comment]
https://github.com/yandex/ClickHouse/pull/3396

**Comment by abyss7** [comment]
Fixed in the master (future v19.8+). How it works:

- Introduced new global setting `stream_poll_timeout_ms`, means, for how long to wait for incoming message before consider that read() has failed. This setting is read once on server start-up and run-time changes are ignored. Zero means instant polling - not a sync behavior.
- Every `stream_flush_interval_ms` / `stream_poll_timeout_ms` rows (not the messages!) there will be a check against the flushing time limit. It guarantees that in the worst scenario, when CH receives one row per one message from Kafka on the edge of polling timeout, the rows still will be flushed every `stream_flush_interval_ms`.
