### ISSUE TITLE
Kafka Engine: Ability to access Key

### ISSUE THREAD

**Issue by xmariachi** [yandex/ClickHouse#2691]
Is it expected to be able to access Key, not just Value, in Kafka Engine?

**Comment by Amper** [comment]
@xmariachi Can you give an example of what using a key might look like?

**Comment by xmariachi** [comment]
Kafka Messages have a Key-Value format. 
In many cases, where there is no need for a key, the message is sent in the value and the key is left null. 
But that is not necessarily the case.

**Comment by Amper** [comment]
@xmariachi Getting the key is not a problem. But I mean, I didn't know how to work with the key should look like from the point of view of the syntax of creating a table with Kafka engine.

**Comment by xmariachi** [comment]
Suggestion: When referencing the fields, you could reference 
`key.field` or `value.field`.
e.g. define fields like `key.field as field, value.otherValue as otherValue`. 
For backwards compatibility, not specifying a prefix would by default mean `value.field`.

**Comment by abyss7** [comment]
Consumed by #5286

**Comment by OlegSchwann** [comment]
It goes to page one of Google, so it's a good place to share experiences.

You can not only **read** the sharding `_key` from Kafka but also **write** sharding `_key`.
To do this, add a `_key String` to the Kafka engine table definition and write to this field. It's important to note that the type must be `String`, otherwise it doesn't work and reports no error.

**Comment by Doppelganger24** [comment]
@OlegSchwann Hello. Your comment helps to me. Thank you a lot! 
But when i set key and value for my message (and send to Kafka) and read it from Kafka topic, so i can see this key in my message value. Why does it happen? And how to avoid it?
