### ISSUE TITLE
10 times mem overhead on complex_key_hashed dictionary ( 227 MiB table eats 2.50 GiB)

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#2738]
```
create table test(a Int64, b Int64, s String) Engine=MergeTree partition by tuple() order by b;
insert into test select rand64(), number, toString(number) from numbers(10000000);
optimize table test partition tuple() final;

```
```
select formatReadableSize(sum(data_compressed_bytes)),  formatReadableSize(sum(data_uncompressed_bytes)) from system.columns where table = 'test' 

┌─formatReadableSize(sum(data_compressed_bytes))─┬─formatReadableSize(sum(data_uncompressed_bytes))─┐
│ 92.10 MiB                                      │ 227.82 MiB                                       │
└────────────────────────────────────────────────┴──────────────────────────────────────────────────┘
```

```
select formatReadableSize(bytes_allocated) from system.dictionaries where name = 'test'
┌─formatReadableSize(bytes_allocated)─┐
│ 2.50 GiB                            │
└─────────────────────────────────────┘
```

```
<?xml version="1.0"?>
<dictionaries>
  <dictionary>
    <name>test</name>
    <source>
      <clickhouse>
        <host>localhost</host><port>9000</port><user>default</user><password/>
        <db>default</db><table>test</table>
      </clickhouse>
    </source>
    <lifetime>300</lifetime>
    <layout>
      <complex_key_hashed/>
    </layout>
    <structure>
      <key><attribute><name>a</name><type>Int64</type></attribute></key>
      <attribute><name>b</name><type>Int64</type><null_value>0</null_value></attribute>
      <attribute><name>s</name><type>String</type><null_value/></attribute>
    </structure>
  </dictionary>
</dictionaries>
```

**Comment by ztlpn** [comment]
Let us count.

For Hashed dictionaries each attribute is stored as a hash table. Because we have a complex key dictionary, the key for these hash tables will have type `StringRef`. The keys themselves will be stored in the arena pool. The hash table value for the `b` attribute will be `Int64`, and for the `s` attribute it will be again a `StringRef` to the separate arena pool that will store the strings themselves.

`bytes_allocated` is a sum of the sizes of arenas and the sizes of hash tables.

Both the key and the `s` attribute occupy around 80MB. Arena pool consists of a list of pools with geometrically increasing size. Total size to accomodate 80MB is almost 128MB. So 256MB is occupied by arena pools.

Next come the hash tables. A hash table is an open addressing table that will try to keep its load factor between 0.25 and 0.5. Conveniently, we can look up the load factor in the `system.dictionaries` table.
```:) select element_count / load_factor from system.dictionaries where name = 'test'

SELECT element_count / load_factor FROM system.dictionaries WHERE name = 'test'

┌─divide(element_count, load_factor)─┐
│                           33554432 │
└────────────────────────────────────┘
```
This gives us two hash tables of size `33554432 = 2^25` cells.

The cell for the `b` attribute contains: the key (`StringRef` - 16 bytes), the hash of the key (8 bytes), the attribute (`Int64` - 8 bytes) = 32 bytes.

The cell for the `s` attribute contains: the key (`StringRef` - 16 bytes), the hash of the key (8 bytes), the attribute (`StringRef` - 16 bytes) = 40 bytes.

This gives us `(32 + 40) * 2^25 = 2.25 GiB` of memory for hash tables. Summing up with 256MiB for arenas we get the value of 2.5GiB that you observe.

**Comment by den-crane** [comment]
hm, the same dictionary but with hashed layout eats 1.37 GiB.

I would prefer more compact but a slower hashed dictionary with collisions and configurable number of buckets which can save memory, because in real production I have a dictionary using 14 GiB RAM with less than 1 GiB table.

**Comment by blinkov** [comment]
@den-crane do you have any further questions?

**Comment by den-crane** [comment]
How it looks on production now:

┌─formatReadableSize(sum(data_compressed_bytes))─┬─formatReadableSize(sum(data_uncompressed_bytes))─┐
│ 703.49 MiB                                     │ 2.41 GiB                                         │
└────────────────────────────────────────────────┴──────────────────────────────────────────────────┘

┌─formatReadableSize(bytes_allocated)─┐
│ 24.38 GiB                           │
└─────────────────────────────────────┘


25 GB RAM on one dictionary. FunFunFun.
