### ISSUE TITLE
Memory alignment issue in IAggregateFunction 

### ISSUE THREAD

**Issue by chenxing-xc** [yandex/ClickHouse#2754]
I'm extending ClickHouse for my scenario, and encounter an issue while looks like to memory alignment of aggregate state in AggregateFunctions.
Taking a look at source code in IAggregateFunctionDataHelper, in-place new  is invoked:
144     void create(AggregateDataPtr place) const override
145     {
146         new (place) Data;
147     }

and the address of place is not guaranteed to be aligned to match Data structure if needed. and 
according to C++ standard, this is undefined behavior, and could cause segment fault while dereferencing it later.

There exists alignOfData and the comment said "Currently not used". I want to know the idea why alignment is not used in ClickHouse and does Yandex encounter core issue related to this problem.

**Comment by alexey-milovidov** [comment]
Yes, aggregate function states in Arena are placed without alignment.
It is Ok most of the time, but some issues are possible:

1. Unaligned memory access is legal for x86 (and AArch 64) in almost all cases. For modern x86_64 CPU there is almost no performance penalty of unaligned access. And more compact memory layout may be actually beneficial.

2. There are some cases when unaligned memory access is illegal in CPU. For example, using aligned SIMD instructions (example: `movdqa` instead of `movdqu`) on unaligned addresses. You will get segfault or bus error. But on modern x86_64 CPUs there is almost no performance penalty from using `movdqu` instead of `movdqa`. Nevertheless we should support alignment of aggregation states if your structs do require alignment.

3. In C++ unaligned placement new is undefined behaviour; compiler may assume that the storage is aligned and it may generate incorrect code. Though it doesn't happen right now. By the way, we want to use UBSan and this issue prevent us from using it.

What we shall do:

1. Start using `alignOfData` method to allocated aggregation states with proper alignment.

2. Thoroughly test any changes in performance and memory usage. It's in question whether performance will increase or drop and whether memory usage increase will be significant.

3. If alignment of all aggregation states will be proven to be non practical for memory usage or performance, we can either:
- define them unaligned for C++ compiler with an attribute;
In this way you still be able to force alignment in cases when it is really needed.
- use alignment conditionally only for UBSan.

**Comment by chenxing-xc** [comment]
Thanks for your response. I will try to align aggregation state in general, and see what happens

**Comment by alexey-milovidov** [comment]
Thank you!

**Comment by alexey-milovidov** [comment]
> @alexey-milovidov Hmm, why do some structs need alignment on their own while the underlying architecture supports unaligned memory access?

Hardware allows unaligned memory access in most cases, but C++ has its own rules.
In C++ compiler may assume that the object is aligned and generate code under that assumption.
If the object is actually not aligned properly, C++ standard provide maximum freedom for the compiler stating it as "undefined behaviour" (to allow as much optimization as possible under proper assumptions).

**Comment by alexey-milovidov** [comment]
gcc-8 started to exploit this rule in Aggregator and AutoArray and this cause failed tests.
(We didn't notice it before because there was no automatic builds with gcc-8 neither with ubsan.)

**Comment by amosbird** [comment]
Oh, I misunderstood the term `on their own`. Thanks

**Comment by alexey-milovidov** [comment]
Just for reference:
https://lemire.me/blog/2012/05/31/data-alignment-for-speed-myth-or-reality/
