### ISSUE TITLE
distributed table data insert

### ISSUE THREAD

**Issue by etah000** [yandex/ClickHouse#2826]
Is it possible to insert data into a distributed table in a distributed way? 
For example, there is a 3-node cluster. I create tables  as follows:

CREATE TABLE NATION_local  ( N_NATIONKEY  Int32 , FakeDate   Date) ENGINE = MergeTree(FakeDate, (N_NATIONKEY), 8192); 
CREATE TABLE NATION AS NATION_local ENGINE = Distributed(perftest_3shards_1replicas,  tpch,  NATION_local, N_NATIONKEY );

The above SQL statements were executed on each nodes.
Is it possible to insert data into table "NATION" from 3 nodes at the same time?

**Comment by alexey-milovidov** [comment]
Yes, you can insert data concurrently to Distributed tables on every server.

PS. Note that the performance will be better if you split your data on application side and then insert into local tables on each server. (This is more complicated but performance is better due to less copying on disk and over network).
