### ISSUE TITLE
Debian repo - up-to-date /testing

### ISSUE THREAD

**Issue by reflection** [yandex/ClickHouse#2922]
Would it be possible to keep /testing updated with '*-testing' releases?  Latest release in repo is currently 18.6.0 instead of 18.11.0

http://repo.yandex.ru/clickhouse/deb/testing

**Comment by alexey-milovidov** [comment]
The release job is supposed to do it automatically but most of the time it just doesn't work. We will make efforts to fix the infrastructure behind the release job.

You can build a package for yourself by running single command on Ubuntu or Debian:
https://clickhouse.yandex/docs/en/development/build/

On the other hand, we have plans to automatically publish packages for "unstable" builds in each pull request by direct links in GitHub comments.

**Comment by alexey-milovidov** [comment]
The release job has been repaired and now testing releases are available at https://repo.yandex.ru/clickhouse/deb/testing/main/

**Comment by reflection** [comment]
@alexey-milovidov please re-open as last successful build looks to be 18.14.1 on Sep 28, 2018: http://repo.yandex.ru/clickhouse/deb/testing/main/

**Comment by alexey-milovidov** [comment]
Testing packages are uploaded automatically when functional tests have passed (for normal release build and for build with sanitizers). This is just small subset of our [tests](https://clickhouse.yandex/docs/en/development/tests/), but for the last week, even that basic set of tests have not passed due to the bug, that was fixed only few hours ago in #3343

**Comment by alexey-milovidov** [comment]
> please re-open as last successful build looks to be 18.14.1 on Sep 28, 2018: 

Now you can see that 18.14.6 has been published.

**Comment by reflection** [comment]
Thanks for the detailed replies.  Makes sense that packages are only uploaded to repo after functional tests pass, and unstable builds from pull requests are pretty cool.

**Comment by arctica** [comment]
Seems like there must be again build issues because I just spent a good while figuring out why an install via the testing repo wouldn't support data skipping indexes as shown in the documentation. The feature seems to have been merged just a week ago and none of the last 2 -testing releases have debian packages built for them.

It also looks like the official docs are built from either the master branch or the testing releases because they include said index feature but the changelog page doesn't mention it and shows last version being 19.1.6 which means there's a mismatch between official docs vs stable release and its own changelog vs content.
