### ISSUE TITLE
URL Connection String for ClickHouse Cluster

### ISSUE THREAD

**Issue by thanhthai3010** [yandex/ClickHouse#3005]
Hi guys,

I just created a ClickHouse cluster with 3 nodes, then I tried to connect these 3 nodes with clickhouse-jdbc, do you guys know any example URL to connect 3 nodes?

Thank you so much.

**Comment by alexey-milovidov** [comment]
@serebrserg

**Comment by serebrserg** [comment]
There is no comprehensive balancing utilities implemented inside
clickhouse-jdbc driver itself. You can try to use
https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java
but I suggest you read the javadoc carefully and review the code to decide
if it fits your needs. Otherwise you can implement the needed balancing by
yourself in application code and create jdbc connections for every single
target server.

**Comment by blinkov** [comment]
Alternatively you could set up your favorite http load balancer (nginx, haproxy, etc.) and use it instead of going to ClickHouse directly. Also there's https://github.com/Vertamedia/chproxy
