### ISSUE TITLE
znodes under /block_numbers seem to grow infinitely

### ISSUE THREAD

**Issue by dqminh** [yandex/ClickHouse#3322]
In our cluster, we regularly dropping old partitions out of the table. However, today i check some of Clickhouse's znodes and look like things under /block_numbers dont seem to be removed.

```
┌─version()─┐
│ 1.1.54388 │
└───────────┘
```

For example, on 1 table which has (date, hour) as primary key, we have

```
get /clickhouse/cluster_name/tables/0/table_name/block_numbers

cZxid = 0x233621bd6e
ctime = Mon Mar 19 17:52:34 UTC 2018
mZxid = 0xdc1e6aab29
mtime = Mon Oct 08 16:20:09 UTC 2018
pZxid = 0xdc1e6aab29
cversion = 4435
dataVersion = 1087
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 0
numChildren = 4435
```

This has 4435 children, while it should really have around 25 children. Should this get cleared when partitions are dropped from the table ? I think this will also make merges much more expensive in term of Zookeeper usages.

cc @vavrusa @alexey-milovidov @bobrik @bocharov

**Comment by vavrusa** [comment]
The latest master switched to ephemeral locks for block numbers, but I'm not sure whether they're cleared when abandoned, @ztlpn would know.

**Comment by ztlpn** [comment]
The problem is not with block number nodes per se, but with partition directories: a block number is allocated by creating an ephemeral sequential node `/<path-to-table>/block_numbers/<partition_id>/block-XXXXXXXXXX` and the directory `/<path-to-table>/block_numbers/<partition_id>` remains even after the partition has been dropped. These nodes can indeed slow down merge selection (although I think only slightly so in case of thousands of nodes).

Unfortunately I cannot think of a simple solution with the current design - simply deleting these nodes can result in data loss if there will be additional inserts into dropped partition. These inserts will begin to allocate block numbers from zero again - this means that a node that hasn't executed DROP PARTITION yet, will have to delete these new blocks, because they will be effectively "before" the DROP PARTITION command in terms of block numbers.

**Comment by dqminh** [comment]
Indeed this is about partition directories, the `/block_numbers/<partition_id>` znodes themselves are empty as expected.

>  simply deleting these nodes can result in data loss if there will be additional inserts into a dropped partition

I havent understood the concern here yet. If the partition is to be dropped and we have very late arriving data as you said, i would expect such data to also be dropped. Also in our cases where we drop the partition months/days later, it would not even be a concern.

**Comment by ztlpn** [comment]
> I havent understood the concern here yet. If the partition is to be dropped and we have very late arriving data as you said, i would expect such data to also be dropped.

The problem is that there no way to guarantee consistency between replicas. One replica can execute DROP PARTITION before the new block arrives (and leave the block intact) and another can execute it after the new block arrives (and drop the block) and there is no way to decide which is the right action.

Of course the probability for it is quite small (especially in your use case) but still I am wary of introducing race conditions, however improbable.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/59507
