### ISSUE TITLE
update benchmark results

### ISSUE THREAD

**Issue by fleapapa** [yandex/ClickHouse#3325]
Is there is a plan to update performance benchmark results of Clickhouse against MemSQL 6.5 which claimed to be **tens of times faster** than its v3.2?

Also, it would be helpful for comparison with similar configurations if **clustered version of Clickhouse** can be added to the comparison table.

Thanks!

**Comment by blinkov** [comment]
We might update it in future, but it has very low priority.

https://clickhouse.yandex/benchmark.html used to be the only benchmark when ClickHouse has been opensourced, but nowadays there are a lot of independent benchmarks (some examples are linked on [official website front page](https://clickhouse.yandex/#independent-benchmarks)), which looks much more credible than that original one (because they are not conducted by the company that stays behind only one of compared products).

If you decide to make such benchmark on your own (or any other benchmark that involves ClickHouse), it'd be appreciated if you publish the results and send us a link.

**Comment by fleapapa** [comment]
Since MemSQL is not open sourced, i have no access to it for benchmark. I thought people at Clickhouse would be more curious than me to learn how MemSQL 6.5 performs against Clickhouse. 

Nevertheless, thanks for the response.

**Comment by alexey-milovidov** [comment]
@fleapapa We have updated the results for MemSQL. In the meantime, it was renamed.
See https://benchmark.clickhouse.com/
The results have been independently validated by the team from SingleStore.
