### ISSUE TITLE
ClickHouse function name case sensitivity

### ISSUE THREAD

**Issue by dfulachier** [yandex/ClickHouse#3704]
When using a tool such as a BI tool to query ClickHouse database (ex: Tableau), we cannot control the tool generated SQL queries, and so the case used for function names.
What I understood about ClickHouse policy on function name case sensitivity is that, standard SQL functions are case insensitive, and specific ClickHouse ones case sensitive.
But some functions, commonly used by lots of SQL engines, are not marked as case insensitive. At least:
pow/power, acos, asin, tan, cos, sqrt, sin, extract, position, upper, lower, atan, substring, if, reverse, abs, log, log2, exp, rand, pi. And this list may not be exhaustive...
So:
- May (at least) these functions be case insensitive?
- Why not considering all functions as case insensitive, as it is the case in most SQL grammars?

**Comment by filimonov** [comment]
I don't know the original motivation, but docs highlight that this is "by design" https://clickhouse.yandex/docs/en/query_language/syntax/#keywords

I think those standard SQL function should be changed to be case-insensitive. 

But changing it now is general - doesn't sound  as a good idea, as in lot of cases CamelCase is used in function names. For case-insensitive naming it should be rather snake_case.
For example:  formatReadableSize looks way better than FORMATREADABLESIZE ( wat? "form at readable size" ?  "for matread able size "?)

**Comment by alexey-milovidov** [comment]
All function that either:
- listed in SQL standard;
- widely used in popular implementations (MySQL, Postgres);
- generated by popular BI tools;
should be made case insensitive.

This is possible in our design, example: https://github.com/yandex/ClickHouse/blob/master/dbms/src/Functions/concat.cpp#L189

**Comment by blinkov** [comment]
Case insensitivity for some additional functions (including listed here) was introduced in #3826, will be available in next release.
