### ISSUE TITLE
Long period after clickhouse-server restart before client connections accepted

### ISSUE THREAD

**Issue by kmatt** [yandex/ClickHouse#3741]
When restarting the clickhouse-server service (v18.14.15 on CentOS 7.5), some nodes in a cluster respond shortly, others can take 10s of minutes or hours beforeaccepting client connections, instead reporting

    Code: 210. DB::NetException: Connection refused: (localhost:9000, 127.0.0.1)

I suspect this may be due to a number of merges queued up when service was shut down. The processes are consuming CPU and disk IO to the service does not appear to be hung. Most of the log messages are in the form of

    2018.12.04 01:25:41.120131 [ 21 ] {} <Trace> testdb.customer_shard (ReplicatedMergeTreeCleanupThread): Execution took 598 ms.                                                │
    2018.12.04 01:25:41.384083 [ 25 ] {} <Trace> testdb.customer_shard (StorageReplicatedMergeTree::mergeSelectingTask): Execution took 735 ms.

It there another indication in the logs that will tell us what the nodes are doing during start up, and is there a way I can diagnose what is causing the long restart cycle?

**Comment by filimonov** [comment]
Slow start problem is known, please see #2278 
Usually, it happens if you have a lot of tables and/or partitions.
Some changes which should improve that situation are already in master and should be released in next versions (no concrete date yet, stay tuned).

Slow shutdown - the reason is 'graceful' finishing of background tasks. In emergency situations, you can force the shutdown, but it can lead to some data corruption.

**Comment by kmatt** [comment]
@blinkov Confirmed it was due to the number of partitions and file count resulting.
