### ISSUE TITLE
dynamic replicas ip address changing

### ISSUE THREAD

**Issue by f41gh7** [yandex/ClickHouse#3845]
Hello, i`ve found in release notes, that clickhouse supports dynamic config reloads and it works perfect for most of options, except changing of replica members and zookeeper servers.

 For instance, i have 2 members: 
`10.0.0.2 hostname0`
`10.0.0.3 hostname1`
 These addresses were wrote to /etc/clickhouse/config.d/remote.xml
 like 
  `<clickhouse-server>

        <shard>

    <replica>
                        <host>10.0.0.2</host>
                        <port>8123</port>
                 </replica>
    <replica>
                        <host>10.0.0.3</host>
                        <port>8123</port>
                 </replica>
        </shard>
</clickhouse-server>
```

 After  changing address of hostname0 to 10.0.0.4, i change address at /etc/clickhouse/config.d/remote.xml.
 
But i still got errors at hotsname1:
`(StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.0.0.2:9009, e.what() = Timeout`

 After restarting  hostname1, everything works fine.

**Comment by ztlpn** [comment]
Hi, 

The problem in your case arises because ClickHouse caches the resolved IP addresses of replicas. The cache should be flushed when there is a surge of network errors, but this functionality is broken now. A workaround is to manually issue the `SYSTEM DROP DNS CACHE` command.

Also note that the IP addresses that you use in the `<remote_servers>` config section are not used for replication, but only for queries to Distributed tables. By contrast, Replicated tables use information that is written to the `/<path_to_table>/replicas/<replica>/host` znode in ZooKeeper to find each other (typically the replica hostname is written there). This information is updated each time the replica reconnects to ZooKeeper.

**Comment by f41gh7** [comment]
awesome, thx!
