### ISSUE TITLE
Question: What should I do when changing zookeeper cluster in config file?

### ISSUE THREAD

**Issue by AlexanderJLiu** [yandex/ClickHouse#3846]
Recently, I want to change the old zookeeper cluster to new one with new ips. Does ReplicatedXXX work correctly with directly replace of zk? Is there sth else should be aware of?

thanks...

**Comment by ztlpn** [comment]
You need to stop insertions into the tables, copy ZooKeeper data to the new cluster, change the `<zookeeper>` section in the config and restart ClickHouse.

The most tedious part is copying the data from the old ZooKeeper cluster to the new one. You should NOT use tools such as https://github.com/ksprojects/zkcopy because they do not preserve the sequential node counters. The easiest way (with some downtime) is to manually copy ZooKeeper snapshots and transaction logs. Another way (with less downtime) is to first add the nodes of the new cluster to the old cluster as replicas and wait for them to sync and then configure them as a separate cluster.

**Comment by AlexanderJLiu** [comment]
@ztlpn Got it, Thanks very much 👍
