### ISSUE TITLE
Clickhouse seems slower when reusing connection

### ISSUE THREAD

**Issue by crakjie** [yandex/ClickHouse#3849]
Reusing connection after a finished query seems slower if we don't send CANCEL packet (packet type 3) at the end of the first query.
I'm surprised because Clickhouse should already know when the query is finished and be ready for the next query.

With a small query time without CANCEL : 70-100ms 
Time with CANCEL : 30-40ms
This time is spent waiting for the first byte of the connection.

**Comment by filimonov** [comment]
related #1403

**Comment by crakjie** [comment]
@filimonov maybe related but it's not in HTTP.

**Comment by ztlpn** [comment]
Hi @crakjie, the issue would be easier to debug if you provide a self-contained test case. I assume that you are using one of the native drivers - can you write a script using this driver + a database schema that clearly reproduces the problem? Thanks.

**Comment by ztlpn** [comment]
A suggestion by @alexey-milovidov: if the query contains some heavy aggregations the slowdown may be due to destructors of aggregate function states. The client thinks that the query execution is over immediately after it receives the EndOfStream packet, but destructors will continue to execute in the background. So if you send the next query immediately, you will experience a slowdown. Sending the Cancel packet can act as an implicit way to wait for destructors to finish.

**Comment by crakjie** [comment]
@ztlpn I'm using my own driver so I can't really send you snippet now.
The query does not use any aggregation. the query is pretty simple 
`select toString(Currency) from (select distinct(Currency) from Values limit 2000)` the table contains 91054 lines an there is just 30 distinct currency.
"immediately" in my case could be minutes.
I tried to change a bit the query to see if it changes the result (removing limit or distinct) it always gives the same result.
What do you mean by "Sending the Cancel packet can act as an implicit way to wait for destructors to finish."

**Comment by ztlpn** [comment]
I have meant that the server must finish running destructors before responding to the Cancel packet, but the Cancel packet doesn't need a response! So the mystery remains. Also, if you wait minutes before issuing the second query and the slowdown still persists, destructors of aggregate functions can't be the reason.

I'm afraid the problem can be hard to debug without the access to your driver because it can be the source of the problem :) Can you reproduce the issue with `clickhouse-client` or another open-source driver?

**Comment by crakjie** [comment]
Ok, found the issue. Thank you for pointing me in the right direction. The problem came from the connection settings. The driver was not using the `tcp no delay` parameter, making it waiting a little time to see if the connection buffer is full. Sending the Cancel must have filled this buffer before the "buffer timeout".
