### ISSUE TITLE
ReplicatedMergeTree table Suggestions for SETTINGS index_granularity

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#3876]
Hi，my cluster qps can over 100W，what value can I set of index_granularity？can I use the default value
 8192

**Comment by den-crane** [comment]
The right value of index_granularity depends of queries and number of rows in a table and RAM of your server.

So if you need to search rows by exact primary key value
(OLTP query -- which is completely against CH nature as OLAP database)
select ... from T where PK_field(s) in (1,2,3)
you can decrease index_granularity but it will cause increased memory consumption (in marks_cache) because of grow of index size.

**Comment by qietingfengling** [comment]
My ram has 16G, there are 100W rows of data per second. Every query has more than 1 hour of data. Do I need to increase the value of index_granularity?

**Comment by den-crane** [comment]
you'd better leave it as default 8192.

**Comment by qietingfengling** [comment]
OK,thanks
