### ISSUE TITLE
How to achieve high availability by querying ReplicatedMergeTree with Distributed

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#3877]
my metrika.xml config as follow
```xml
<clickhouse_remote_servers>
    <shard_one>
        <shard>
            <weight>1</weight>
            <replica>
                <host>host-ch-01</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <weight>1</weight>
            <replica>
                <host>host-ch-03</host>
                <port>9000</port>
            </replica>
        </shard>
    </shard_one>
    <shard_two>
        <shard>
            <weight>1</weight>
            <replica>
                <host>host-ch-02</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <weight>1</weight>
            <replica>
                <host>host-ch-04</host>
                <port>9000</port>
            </replica>
        </shard>
    </shard_two>
</clickhouse_remote_servers>


<zookeeper-servers>
  <node index="0">
    <host>host-zk-01</host>
    <port>2181</port>
  </node>
</zookeeper-servers>

<macros>
    <replica_group>01</replica_group>
    <replica>host-ch-01</replica>
</macros>
```

if the shard_one one of node `host-ch-01` unusable，the global shard_one can not use，My configuration is right?

**Comment by den-crane** [comment]
you are doing something confusing. 
2 shard * 2 repica :

```
<yandex>
    <remote_servers>
        <cluster2shard2replica>
                <shard><internal_replication>true</internal_replication>
                            <replica><host>clickhouse-primary1</host><port>9000</port></replica>
                            <replica><host>clickhouse-secondary1</host><port>9000</port></replica>
                </shard>
                <shard><internal_replication>true</internal_replication>
                            <replica><host>clickhouse-primary2</host><port>9000</port></replica>
                            <replica><host>clickhouse-secondary2</host><port>9000</port></replica>
                </shard>
        </cluster2shard2replica>
    </remote_servers>
</yandex>
```

**Comment by qietingfengling** [comment]
I think I get you idea,thanks

**Comment by qietingfengling** [comment]
Hello, I have tried this configuration, but I am not very clear about the role of zookeeper in this configuration? The statement I created for the ReplicatedMergeTree table is ENGINE = ReplicatedMergeTree('/ch/replica_{replica_group}database_name/table_name', '{replica}'..., how should I change the parameters replica_group and replica in macros?

**Comment by ztlpn** [comment]
You can use the shard number as `replica_group` (`01`, `02`, etc.) and the hostname (`host-ch-0X`) as `replica`.

ZooKeeper is needed for Replicated tables. In your current configuration there is only one ZooKeeper node. This configuration is not fault-tolerant - if the ZooKeeper node goes down, the Replicated tables cannot process INSERTs. A better configuration is a cluster of three ZooKeeper nodes.

Also, your ZooKeeper server is colocated with the ClickHouse servers. This configuration can work, but it is strongly not recommended, because ZooKeeper needs fast dedicated storage for its transaction logs, otherwise latency will be abysmal.

As for the `clickhouse_remote_servers` config, you have configured 2 clusters of 2 shards (with 1 replica in each shard). Instead, as @den-crane suggests, you probably need to configure 1 cluster of 2 shards with 2 replicas each.

**Comment by qietingfengling** [comment]
I think I understand it,thanks
