### ISSUE TITLE
IN operator not working with Decimal values.

### ISSUE THREAD

**Issue by LittleMaverick** [yandex/ClickHouse#3884]
```
 CREATE DATABASE test;
  CREATE TABLE temp 
    (
        name1 Nullable(Decimal(38,12))
    ) ENGINE = Memory;
   
    INSERT INTO test.temp VALUES (5, 10);
```

I try to execute such query:
`    SELECT * FROM test.temp WHERE name1 IN (toDecimal128(5, 12))` 

But it throws an exception:
Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section. Expected: Decimal(38, 12). Got: Decimal128, e.what() = DB::Exception.

**Comment by den-crane** [comment]
hm, the issue seems in Nullable
 
workaround:
INSERT INTO temp VALUES (5), (10);
SELECT * FROM temp WHERE name1 IN ( cast(5 as Nullable(Decimal(38,12)))  )

5.000000000000
--

**Comment by ztlpn** [comment]
@chertus can you take a look?

It seems that [this function](https://github.com/yandex/ClickHouse/blob/c77930fe30824ff09a005b11ebd23d4d74c6d6ad/dbms/src/Interpreters/convertFieldToType.cpp#L106) should support conversions from other Decimal types.

E.g. this works (because types are the same, but anyway, the `convertDecimalType` function should support this case too):
`SELECT toDecimal128(1, 12) IN toDecimal128(1, 12)`
but the following don't work:
`SELECT toDecimal128(1, 12) IN toDecimal128(1, 24)`
`SELECT toDecimal128(1, 12) IN toDecimal64(1, 12)`

**Comment by 4ertus2** [comment]
#5350
