### ISSUE TITLE
ReplicatedMergeTree: Too many parts (300). Merges are processing significantly slower than inserts

### ISSUE THREAD

**Issue by ggservice007** [yandex/ClickHouse#4050]
I can not insert data into ReplicatedMergeTree.

```cmd
exception code: 252, 
Code: 252, e.displayText() = DB::Exception: 
Too many parts (300). Merges are processing significantly slower than inserts.
, e.what() = DB::Exception
```

**Comment by blinkov** [comment]
How frequently do you insert?

**Comment by ggservice007** [comment]
The MergeTree is ok. 

ReplicatedMergeTree can not work even 70 items/s.

**Comment by ggservice007** [comment]
I am not using batch.

**Comment by blinkov** [comment]
Then that's the reason for the error you see.

**Comment by M1hacka** [comment]
+1. I have batches. And it worked ok on MergeTree table. But when I decided to use ReplacingMergeTree no merges are done. Even if I stop INSERTs at all and wait for a day...

**Comment by den-crane** [comment]
> ReplicatedMergeTree can not work even 70 items/s.
Zoo MUST be at different physical server. CH utilitizes all 200% I/O and causes Zoo I/O starvation.
Try to install zookeeper on dedicated instance with SSD disks.

**Comment by den-crane** [comment]
> +1. I have batches. And it worked ok on MergeTree table. But when I decided to use ReplacingMergeTree no merges are done. Even if I stop INSERTs at all and wait for a day...
> P. s. I do single insert in 10 seconds. But it has small amount of data (less than 1 mb on disc, according to system.parts). I suppose that may cause the problem.

CH designed to use monthly partitions. The only one explanation to your issue is super tiny partitions. Please show the table DDL (at least partition by section).

**Comment by M1hacka** [comment]
Firstly, I used MergeTree engine with standard toYYYYMM('date') partitioning. It worked.
Than I changed MergeTree to ReplicatedReplacingMergeTree with (`app_id`, `toYYYYMM('date')` ) partitioning. It's more effective for me in SELECT operations. But partitions grew fast and I decided to make partitioning back: standard  `toYYYYMM('date')`
Now it's  ReplicatedReplacingMergeTree with ( `toYYYYMM('date')` ) . But number of partitions is still growing up to limit.
It seems that my problem may be caused by replication in some way? as I see same problem on ReplicatedCollapsingMergeTree too, which worked well without replication (with same partitioning), [This issue](https://github.com/yandex/ClickHouse/issues/4049) describes another strange problem with replication, and I suppose it may be connected

**Comment by filimonov** [comment]
See #1510 #3174 #2811 #4199 #6720

**Comment by simPod** [comment]
@den-crane Hi, can you please elaborate on 

> CH designed to use monthly partitions. The only one explanation to your issue is super tiny partitions. Please show the table DDL (at least partition by section).

What does it imply? Is is wrong to have partitioning based on days? I'm asking because I have daily parts, each is over 1 TB.

-----------------

> Zoo MUST be at different physical server. CH utilitizes all 200% I/O and causes Zoo I/O starvation.
Try to install zookeeper on dedicated instance with SSD disks.

I have ZK logging into dedicated SSD on the same instance. So ZK and CH share the instance but not disks. According to what you said, it should be enough. Am I right?

Thanks!

**Comment by den-crane** [comment]
>Is is wrong to have partitioning based on days?
>I'm asking because I have daily parts, each is over 1 TB.


@simPod it not your case. You parts are not tiny (1TB rather huge). Daily partitions is OK, probably in your case they are strongly recommended.

>So ZK and CH share the instance but not disks. 
>According to what you said, it should be enough. Am I right

In most cases yes (while CH does not eat all 100% all time).
