### ISSUE TITLE
What is the status of LowCardinality feature, where is it documented ?

### ISSUE THREAD

**Issue by healiseu** [yandex/ClickHouse#4074]
Hi, I have searched for official documentation of this feature, it is quite important on the project I am working, but I have not found any yet, it is not described in data types, please correct me if I am wrong.

There has been a similar question here, #2903, half a year ago, but the answer from @alexey-milovidov is not very specific. I want to find out details on this feature, specifically I want to know.

1) What are the differences from ENUM types ?
2) Can you give a brief explanation on how it supplements column compression ?
2) When is it used ? How low, in numbers, the cardinality of a field should be to qualify for its use ?
3) What are the current restrictions on its use, e.g. INSERT, Engines, etc ?
4) Is it safe to use the latest version 18.16.1 and include this feature ?

Can somebody answer these quickly ?

Thank you

PS: Change log is often updated with information about `LowCardinality`. That shows I think how important this feature is. It also seems it has matured, but unfortunately it has not been documented.

**Comment by alexey-milovidov** [comment]
> What are the differences from ENUM types?

LowCardinality data type builds dictionaries automatically. It can use multiple different dictionaries if neccessarily.

> Can you give a brief explanation on how it supplements column compression?

It works independent of (generic) columns compression. Columns with LowCardinality data type are subsequently compressed as usual. The compression ratio of LowCardinality columns in comparison to data in text format may be significantly better then without LowCardinality but sometimes it is the same. The main benefit is data processing speed, because data is processed while being dictionary encoded (you can imagine it as the data is not fully decompressed before being processed: only generic decompression is applied and the data remains in LowCardinality form).

> When is it used ? How low, in numbers, the cardinality of a field should be to qualify for its use ?

Rule of thumb: it should make benefits if the number of distinct values is less that few millions.

But actually, the implementation is way smarter. If the number of disting values is pretty large, the dictionaries became local: several different dictionaries will be used for different ranges of data. For example, if you have too many distinct values in total, but only less than about a million values each day - then queries by day will be processed efficiently... and queries for larger ranges will be processed rather efficient.

> What are the current restrictions on its use, e.g. INSERT, Engines, etc?

It is supported for all table types and for all query types. All functions and aggregate functions are also supported automatically. I don't remember any remaining restrictions, will ask @KochetovNicolai 

> Is it safe to use the latest version 18.16.1 and include this feature?

The feature is almost production ready. Only single known issue remains: https://github.com/yandex/ClickHouse/issues/4038 and it is going to be fixed in 18.17. Though we have not started to use LowCardinality feature in production at Yandex.

**Comment by KochetovNicolai** [comment]
There is no restrictions on LowCardinality usage. More information you can find in [this presentation](https://github.com/yandex/clickhouse-presentations/blob/master/meetup19/string_optimization.pdf).

**Comment by healiseu** [comment]
@alexey-milovidov  and @KochetovNicolai thank you for the briefing,  dictionary encoded processing is an extremely important issue in database technology. I foresee that there is still going to be significant progress on techniques based on this. It's all about the power of abstraction and representation that is deeply rooted in semiotics.

TriaClick, the next release of TRIADB project with Clickhousse I am working on is based on similar encoding where among other things it solves to a large extent the problems of data modeling, namespace, joins and missing data. This is achieved by assigning numerical dimensions to data models, entities, attributes and instances of them. In that case I discovered that Clickhouse partitioning system is a perfect fit. I will make an effort to use LowCardinality and let you know as I think this will make TriaClick associative, semiotic, hypergraph technology to run faster. 

I had a quick look at Kochetov Nikolai presentation, that helps, but I hope there are also going to be code examples to study various cases in testing repositories of clickhouse distribution.
