### ISSUE TITLE
 icu/glib static linking in libcommon

### ISSUE THREAD

**Issue by yannick** [yandex/ClickHouse#41]
is it necessairy to statically link icu and glib in libcommon?
this makes it hard to build ClickHouse on other Distributions.

**Comment by alexey-milovidov** [comment]
It is for more easy deployment.
With static linking it has runtime dependencies only on libc.

To build ClickHouse on other distributions, there are several ways:
1. Build ICU, GLib2 from sources and use compiled static libraries (install to /usr/local as default: libraries is searched there).
2. Change static linking to shared (.a to .so) in libs/libcommon/CMakeLists.txt

We don't have official packages for other distributions, but see below...

To install ClickHouse on other distributions, you often don't need to rebuild it and could use .deb packages. 
So, package for Trusty depends on libc6 2.19..2.20 and package for Precise depends on libc6 2.15..2.16.
To determine libc version of your system, run `ldd --version` or run `/lib/x86_64-linux-gnu/libc.so.6` or `/lib64/libc.so.6` as executable.
If you have matching version, just install debian packages by unpacking manually:

```
ar x clickhouse-server-base_1.1.53988_amd64.deb
sudo tar -x -C / -f data.tar.xz

tar xf control.tar.gz
sed -r -i 's/update-rc.d.+/true;/' ./postinst
sudo ./postinst

ar x clickhouse-server-common_1.1.53988_amd64.deb
sudo tar -x -C / -f data.tar.xz

ar x clickhouse-client_1.1.53988_amd64.deb
sudo tar -x -C / -f data.tar.xz

sudo service clickhouse-server start
```

Also it's possible to build ClickHouse on Ubuntu Trusty with experimental option to depend only on older libc.
If you need it, do the following steps:
1. Temporarily obtain a server, VM or container with Ubuntu Trusty.
2. Build ClickHouse according to the instructions: https://github.com/yandex/ClickHouse/blob/master/doc/build.md,
   but instead of `./release --standalone` do `GLIBC_COMPATIBILITY=1 ./release --standalone`.
3. Install generated packages on target system with manual unpacking.

**Comment by mkevac** [comment]
How can you specify dir where libicu is located? If it's not in system dir.

**Comment by alexey-milovidov** [comment]
You may add 'link_directories' entry into root CMakeLists.txt file.

**Comment by zjjfly** [comment]
hi,I followed your advice above to build clickhouse on Ubuntu Trusty ,and i want to start up clickhouse on centOS 5.5 whose glibc is 2.5.then It shows that it need glibc 2.10.so,i try to upgrade glibc to 2.10,but it seems that the 2.5 glibc is dependency of many things in centos5.5.Is there a way to start clickhouse on centos5.5?

**Comment by alexey-milovidov** [comment]
Could you afford at least CentOS 6?
It is possible to make compatibility with glibc 2.5, but it requires additional amount of work.

**Comment by zjjfly** [comment]
I just copy file  which glibc-2.14 installed, to centos5.5 ,now the glibc  update to 2.14.I dont know whether this approach is right,but it works.
