### ISSUE TITLE
min(datetime) if table is empty

### ISSUE THREAD

**Issue by aCLr** [yandex/ClickHouse#4333]
Кажется, что такая дата немного некорректна. Хотя бы потому, что не может быть 0 месяца и 0 дня.
```
86601dc03e45 :) create table test (updated_at DateTime) Engine=Log;

CREATE TABLE test
(
    updated_at DateTime
)
ENGINE = Log

Ok.

0 rows in set. Elapsed: 0.022 sec. 

86601dc03e45 :) select count() from test;

SELECT count()
FROM test 

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.020 sec. 

86601dc03e45 :) select min(updated_at) from test;

SELECT min(updated_at)
FROM test 

┌─────min(updated_at)─┐
│ 0000-00-00 00:00:00 │
└─────────────────────┘

1 rows in set. Elapsed: 0.003 sec. 

```

**Comment by alexey-milovidov** [comment]
"0000-00-00 00:00:00" is a special value that indicates the global default value of `DateTime` data type.

Aggregate functions in ClickHouse return non-Nullable data type if were called for non-Nullable arguments (this contradicts the SQL standard and we can eventually implement an option to change this behaviour). That's why we have to return some DateTime value instead of NULL. The lowest DateTime value is dependent on time zone. For example, for Europe/Moscow it is `1970-01-01 03:00:00`. To avoid confusion, one special DateTime value (that is represented by zero unix timestamp) is reserved for this purpose and always displayed as "0000-00-00 00:00:00".

PS. The idea of using "0000-00-00 00:00:00" value was initially beared from MySQL.
