### ISSUE TITLE
How to control value of `Showed first 10000` in ch-client

### ISSUE THREAD

**Issue by jangorecki** [yandex/ClickHouse#4489]
Is there any setting that controls default number of max rows printed to console by clickhouse-client?
If there is, such info could be added to https://clickhouse.yandex/docs/en/interfaces/formats/ where user can land on attempt to search for "Showed first 10000".
To be precise I am asking for client-side setting, so changing that value must not impact query optimization processes.

**Comment by den-crane** [comment]
```
set output_format_pretty_max_rows = 3;
select * from numbers(100);

SELECT *
FROM numbers(100)

┌─number─┐
│      0 │
│      1 │
│      2 │
└────────┘
  Showed first 3.

100 rows in set. Elapsed: 0.001 sec.
```

**Comment by den-crane** [comment]
```
select * from numbers(100) format Null;

SELECT *
FROM numbers(100)
FORMAT Null
100 rows in set. Elapsed: 0.001 sec.

```

**Comment by jangorecki** [comment]
Thanks

**Comment by Mall0c** [comment]
For anyone who comes across this: using clickhouse-client, issuing a query with a large result set and having output_format_pretty_max_rows set to a large number, like the default 10k, can obviously slow down the performance of the query as such and tell you a wrong number of rows processed per second, total time and so on, because the time it takes to print the data to the terminal is taken into account for these metrics too. So if you wonder, why your query takes so long or if you just quickly want to test a query in clickhouse-client, set output_format_pretty_max_rows to something like 10 or 1.

**Comment by alexey-milovidov** [comment]
Or `FORMAT Null` to avoid sending data to client at all.
