### ISSUE TITLE
Wrong __asm__ commands leading to broken build with AVX enabled

### ISSUE THREAD

**Issue by podshumok** [yandex/ClickHouse#4508]
```c++
__asm__ volatile ("vaddpd %%ymm0, %%ymm0" : : : "ymm0");
```
in `libs/libdaemon/src/BaseDaemon.cpp`

with `gcc (Gentoo Hardened 7.3.0-r3 p1.4) 7.3.0` I've got 

```
Error: number of operands mismatch for `vaddpd'
```

**Comment by 4ertus2** [comment]
Could you make a pull request with a fix? ;)

**Comment by podshumok** [comment]
My asm-fu is not good enough unfortunately

**Comment by 4ertus2** [comment]
In this place we just try to call this instruction on any registers with any data. Just to detect that CPU supports AVX. The problem is vaddpd expects 3 registers (2 sources and one result), but __asm__ construction in this line means something else (probably 2 source registers and 1 result). If you can change this line to something that starts with '__asm__ volatile ("vaddpd ' and pass compilation, you asm-fu is good enough :)

**Comment by patricklauer** [comment]
```
sed -i -e 's/vaddpd %%ymm0, %%ymm0/vaddpd %%ymm0, %%ymm0, %%ymm0/' libs/libdaemon/src/BaseDaemon.cpp
```
This makes the compiler happy enough to proceed, I have no idea about the semantics of it.
