### ISSUE TITLE
clickhouse source code version management

### ISSUE THREAD

**Issue by etah000** [yandex/ClickHouse#4726]
Now we have three branch are actively progressing, v19.1, v19.3 and master. I am a little confued. Which version is more stable? The bug fix patches in branch v19.1 or v19.3  are also applied in branch "master"。

After some time, we tag a revision with two tags, for example: v19.1.6-testing, v19.1.6-stable.  Do you have any special consideration  to tag the same version with different tags?

Can anyone give a simple explanation？ Thanks a lot.

**Comment by blinkov** [comment]
Basically it's recommended to upgrade to latest release marked "stable" as soon as you can (with max overall version number, reading from left to right). In non-production environments you can update to releases marked "testing" to notice issues earlier and report/fix them in advance.

You should take extra care when upgrading between major versions (different branches, first two parts of version number) since there are new features and possibly important changes, make sure to check [changelog](https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md) for any notes on upgrading.

Installing newer minor versions from same branch is safer since only bug fixes or security fixes are backported. So if you can't keep up with major versions for some reason, at least try to install minor updates as soon as possible.

**Comment by alexey-milovidov** [comment]
> After some time, we tag a revision with two tags, for example: v19.1.6-testing, v19.1.6-stable. Do you have any special consideration to tag the same version with different tags?

Testing version goes to stable without any changes to code - as soon as it was tested well enough. You can consider it as "release candidate". Most of the tests are performed automatic for each commit and pull request (you can see green marks in commit list), but it is not enough. We also install testing version to the testing environment of [Yandex.Metrica](https://metrica.yandex.com/) service. If it doesn't go well enough, we just abandon the current testing release, fix the bugs and create next release.
