### ISSUE TITLE
Confused about server binaries size (deb)

### ISSUE THREAD

**Issue by nitso** [yandex/ClickHouse#4737]
Hello. 
I'm a little confused about clickhouse binaries size. I was going to upgrade version from 18 to 19 and noticed deb packets size: 

    clickhouse-server-base_18.16.1_amd64.deb                339M
    clickhouse-server-base_19.4.1.3_amd64.deb               734M

Two questions:
1) Is it correct that size doubles for a major version?
2) What is included in a distribution that takes ~1.8G for a server binary (/usr/bin/clickhouse unarchived) in 19.4.1.3 version?

**Comment by den-crane** [comment]
you need only 3 debs

```
 103M Mar 18 12:57 clickhouse-common-static_19.5.1.122_amd64.deb
 12K Mar 18 12:57 clickhouse-client_19.5.1.122_all.deb
 24K Mar 18 12:57 clickhouse-server_19.5.1.122_all.deb
```

**Comment by alexey-milovidov** [comment]
`сlickhouse-server-base` is an obsolete package that has embedded debug info.
Most of its size is debug information. There is a lot of debug info due to large number of C++ template instantiations. You can obtain debug info separately from `clickhouse-common-static-dbg` package.

The size of `clickhouse-common-static` package (the main package with `clickhouse binary`) has increased from 69M (for 18.16) to 102M (for 19.4). This is Ok and caused by addition of new features (mostly for HDFS and Parquet integration).

**Comment by alexey-milovidov** [comment]
PS. JFYI, number of commits since version 18.16 was increased by 14% and number of CLOC in `dbms` directory - by 9%.

**Comment by nitso** [comment]
Thanks a lot for explanation.
