### ISSUE TITLE
Usage of HashTable with std::is_trivially_copyable<Value>::value == false

### ISSUE THREAD

**Issue by Gladdy** [yandex/ClickHouse#4906]
Background, @4ertus2 and me ran into a (probable) issue regarding storing an object with managed storage in a HashTable (https://github.com/yandex/ClickHouse/pull/4875), though at the time also some multithreading bugs were present which might have affected the observed behaviour as well.

Bug question:
In HashTable.h it mentions that the values in the HashTable must be memmovable: 
```
/** NOTE HashTable could only be used for memmoveable (position independent) types.
  * Example: std::string is not position independent in libstdc++ with C++11 ABI or in libc++.
  */
```
Now std::memmove requires the value to be TriviallyCopyable (https://en.cppreference.com/w/cpp/string/byte/memmove). 

When a ran a quick build which added a `static_assert( std::is_trivially_copyable<Value>::value, "msg");` to the HashTable declaration, it only flagged up a single case (before the build failed and terminated): `ComplexKeyCacheDictionary.cpp:172`, which instantiates a HashTable with a std::vector<unsigned> as the value. Is this intended to work? Is it just a dormant bug that would only appear when the HashTable would exceed a certain size and would need to be resized and hence the objects moved?

**Comment by alexey-milovidov** [comment]
`std::vector` actually can be copied with memcpy/memmove correctly.

Although it is not guaranteed by the standard, we assume that it contains three fields that are sizes or pointers to the single allocated memory region. When we copy these fields and forget about old object, nothing bad can happen.

`std::is_trivially_copyable<std::vector<...>>` is false, because it has non-trivial copy-ctor and move-ctor.
(copy-ctor has to copy the elements, and move-ctor has to invalidate old instance)

The assumption may break, for example, if `std::vector` will be implemented with "small object optimization" similar to `std::string` and will contain pointer to itself ("stack" space) instead of allocated memory region. But we feel ourself fine as of now.

**Comment by alexey-milovidov** [comment]
Summary: no bug exists, but we rely on weak assumption.
