### ISSUE TITLE
Insert atomicy with insert into MergeTree from select LOG vs StripeLog -- UB or not?

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#5148]
We are trying to achieve atomicity with insert from select and found out it probably possible with Log engine +  max_threads=1 and it's not possible StripeLog? 
The question is it expected behaviour?

19.5.3.8

create table xx (a Int64) engine = Log;
insert into xx select number from numbers(5000000);
insert into xx select number+5000000 from numbers(5000000);
create table xxm (a Int64) engine = MergeTree order by a;
set max_block_size=20000000;
set max_threads=1;
insert into xxm select throwIf(a=9000000) from xx;
select count() from xxm;
**0 rows in set.**

drop table xxm;
drop table xx;

`re-start clickhouse-client to reset max_block_size`

create table xx (a Int64) engine = StripeLog;
insert into xx select number from numbers(5000000);
insert into xx select number+5000000 from numbers(5000000);
create table xxm (a Int64) engine = MergeTree order by a;
set max_block_size=20000000;
set max_threads=1;
insert into xxm select throwIf(a=9000000) from xx;
select count() from xxm;
**7097152**

Though it would be nice to have some parameter like max_insert_block_size to make `insert select` processed with atomicity.

**Comment by alexey-milovidov** [comment]
The reason is that `max_block_size` has no effect on `StripeLog` and `Memory` engine. Data in `StripeLog` and `Memory` is stored in blocks. And data is read in the same blocks as was stored in a table, regardless to `max_block_size`.

In contrast, in `Log` and `TinyLog`, data is stored in almost contiguous columns that can be read in any desired splices. The same is for `MergeTree` with several exceptions.

But when you do `INSERT SELECT` query (or insert via native protocol), small blocks are merged together before insertion and it is controlled by `min_insert_block_size_rows` (default: 1048576) and `min_insert_block_size_bytes` (default: 256 MiB). It means, that even if blocks in `StripeLog` table are small, INSERTed blocks will have reasonable size.

You want to manually increase INSERT block size to 20000000 for atomicity, but the value of `min_insert_block_size_rows` is not enough. To get the desired result, you have to increase the value of `min_insert_block_size_rows` setting to 20000000 and set `min_insert_block_size_bytes` to some large value (example: 10 GiB) or reset it to zero (to disable threshold in bytes).

**Comment by alexey-milovidov** [comment]
To get atomicity for all block sizes:
```
SET 
    max_insert_block_size = 10000000000,
    min_insert_block_size_rows = 10000000000,
    min_insert_block_size_bytes = 10000000000000;
```
