### ISSUE TITLE
 Help: Another server instance in same directory is already running

### ISSUE THREAD

**Issue by lzy305** [yandex/ClickHouse#5225]
when i run a query.  Service restart. And then I see the error log. Message:

2019.05.08 22:09:40.754275 [ 1 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/data/status. Another server instance in same directory is already running.
2019.05.08 22:10:11.005677 [ 1 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/data/status. Another server instance in same directory is already running.
2019.05.08 22:20:04.191684 [ 1 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/data/status. Another server instance in same directory is already running.
2019.05.08 22:20:34.507849 [ 1 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/data/status. Another server instance in same directory is already running.

**Comment by filimonov** [comment]
So probably ClickHouse server is already running?
Check the contents /data/clickhouse/data/status file

**Comment by lzy305** [comment]
I Solve it. THANK you!

**Comment by sliontc** [comment]
Got same issue, how to solve it ? @lzy305

**Comment by alexey-milovidov** [comment]
@sliontc Check the logs.

If it will not help, run clickhouse-server manually with the command:
```
sudo -u clickhouse /usr/bin/clickhouse server --config-file /etc/clickhouse-server/config.xml
```

**Comment by ddoneGit** [comment]
I meet this question too.the real reason is that we had started one more clickhouse-server.
if you " ps -ef | grep clickhouse-server " and "service clickhouse-server status" you will find 
the pid is different.so you just need kill the started pid and restart clickhouse-server  
this is my solution 
cat ./status 
ps -ef | grep clickhouse-server
kill -9 $pid
service clickhouse-server start
