### ISSUE TITLE
Setting `input_format_csv_empty_as_default`

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5349]
The setting affects parsing data from CSV format.

With current behaviour, if CSV has unquoted empty field, it is parsed as empty string (for String data type) or will lead to parse error (for other data types).

The user wants to be able to omit fields in CSV (for any data type) and expects it to be interpreted as default. We will make it possible with the proposed setting, and this setting will have chance to be enabled by default.

Design decisions:

1. This setting is available only for CSV, not for TSV. Because TSV doesn't allow to quote fields and the user will lose the possibility to insert empty string with this setting enabled (if the default expression is not an empty string). We can make a separate setting `input_format_tsv_empty_as_default`.

2. For Nullable data types, the "default" default expression is NULL. It means, that there is no need for separate "empty as NULL" behaviour, because it will be available automatically.

3. There is related but independent feature: allow to parse NULLs for non-Nullable types and treat them as default. This is also relevant for VALUES format. This feature is out of scope of this task.

4. There is related but independent feature: allow to parse unquoted NULL literals in CSV as NULLs. Currently only \N is supported for NULLs and unquoted NULL is parsed as 'NULL' string. This feature is out of scope of this task.

5. Complex default expressions must be supported. Look at JSONEachRow format for example (this is solved in task #75).

Related: #86, #79, #469, #5232.

**Comment by akuzm** [comment]
This is going to take some time. Currently, there is no clear stage that parses a CSV row to an array of plain text column values. I'll need to factor out this step, so that we can make decisions based on the plain text values, e.g., substitute default values for empty plain text. 

For the record, now CSV is parsed as follows: the delimiters are parsed by CSVRowInputStream, and then additional unescaping is done by each individual data type (IDataType::deserializeTextCSV), along with parsing the resulting plain text. A side effect of this approach is that there is no point where we know a plain text value of a column.

**Comment by alexey-milovidov** [comment]
> This is going to take some time. Currently, there is no clear stage that parses a CSV row to an array of plain text column values. I'll need to factor out this step, so that we can make decisions based on the plain text values, e.g., substitute default values for empty plain text.

You cannot.

**Comment by akuzm** [comment]
There are two related bugs that still need to be fixed: #5666, #5653.
