### ISSUE TITLE
Compound IP Type

### ISSUE THREAD

**Issue by ifoo** [yandex/ClickHouse#5462]
CH currently supports specialized types for IPv4 and IPv6, including functions for CIDR testing ( IPv4CIDRtoIPv4Range and IPv6CIDRtoIPv6Range e.g.).

Would it be feasible to support a compound IP type that could hold both v4 and v6 addresses including support for CIDR operations? The data I'm getting is mixing v4 and v6 addresses and it would be hard to split them up into different fields.

If this is not feasible or does not fit the roadmap, what would be the best alternative(s)? Using FixedString(16) and some magic conversion logic during queries?

A typical use case would be to check if an IP address is in the private range (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fd00::/8 for example).

**Comment by filimonov** [comment]
There is already such a compound IP type, you can store both of them as IPv6.
Just because any IPv4 has it's unique IPv6 mapping:

IPv4 IP address: 191.239.213.197
IPv4-mapped IPv6 address: ::ffff:191.239.213.197

All you have to do is add ::ffff: in front of your IPv4 address.

**Comment by mzealey** [comment]
Yes, however storing the value as a `String` uses less space than as a `FixedString(16)` if the data is predominantly IPv4. Perhaps could do this and then some sort of detection based on length being 4 or 16 bytes to figure out what the input/output format would be?

**Comment by alexey-milovidov** [comment]
> Yes, however storing the value as a String uses less space than as a FixedString(16) if the data is predominantly IPv4.

That's only partially correct.

FixedString(16) occupies 16 bytes in memory.
String with 4 bytes will store 4 bytes + 1 trailing zero byte + 8 byte size = 13 bytes.
That's only 3 bytes difference (19%), not so much and I don't think it will pay increased CPU usage.

On disk, FixedString(16) with IPv6-mapped IPv4 data will usually compress almost the same as IPv4, because first 12 bytes `::ffff` will repeat and even the lightest default compression (LZ4) is perfect detecting repeating matches with length >= 4 bytes.

**Comment by mzealey** [comment]
In my tests, on disk when we use String to store 4 bytes of data ipv4 ip address, the compressed size is roughly 1 byte (~2.3 bytes) smaller than using `FixedString(16)`. I'm not using the `::ffff` style syntax just storing 4 or 16 bytes (99% ipv4).
