### ISSUE TITLE
ALTER column datatype timeouts. What's the best way?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#5592]
When trying to change column's datatype
```
:) alter table sflow modify column column_1 LowCardinality(UInt8);

ALTER TABLE t1
    MODIFY COLUMN
    `column_1` LowCardinality(UInt8)
```
Getting response
```
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

Is the only way to increase timeout / recreate the table?

**Comment by den-crane** [comment]
>Timeout exceeded while receiving data from server. 

This client's timeout because of zero network activity. You can tune receive_timeout in client config.

Alter was not canceled. It worked until the end. 

>Is the only way to increase timeout / recreate the table?
you can do nothing because nothing bad happened. You just got several false errors. 
And you can increase receive_timeout / send_timeout in arguments of client or /etc/clickhouse-client/config.xml

**Comment by den-crane** [comment]
LowCardinality(UInt8) -- is nonsense. It is ALWAYS worse than UInt8.
LowCardinality makes sense only for String type.

**Comment by simPod** [comment]
_Yea, sorry, using it with strings always._

Thanks for clarifying.
