### ISSUE TITLE
Can MemoryTracker be optimized?

### ISSUE THREAD

**Issue by nicelulu** [yandex/ClickHouse#5844]
When I used spark and JDBC to write data, CPU usage:

![image](https://user-images.githubusercontent.com/18606973/60572568-7553bf00-9da8-11e9-9261-e7688e5ced13.png)
![image](https://user-images.githubusercontent.com/18606973/60572674-b2b84c80-9da8-11e9-9ce2-37b4a7a81bed.png)

**Comment by akuzm** [comment]
Could you make a flame graph so that we can see where the memory allocations are coming from? 
This repo has the tools and the explanation on how to do it https://github.com/brendangregg/FlameGraph

Generally speaking, MemoryTracker does impose some overhead because it increments a global variable atomically. But if this becomes a bottleneck, we probably should modify the calling code not to do so many allocations.

**Comment by alexey-milovidov** [comment]
I have seen similar issue but with only about 10% spent in MemoryTracker.
By the way, do you use many LowCardinality columns?

**Comment by nicelulu** [comment]
Thank you for your reply.
  Here is the flame graph.I did use many LowCardinality columns, about 50.
![image](https://user-images.githubusercontent.com/18606973/60803816-a79d5c00-a1ae-11e9-95da-c8e6c9b37b92.png)

[writeData.svg.zip](https://github.com/yandex/ClickHouse/files/3367911/writeData.svg.zip)

**Comment by alexey-milovidov** [comment]
And it was optimized by @4ertus2
