### ISSUE TITLE
Add 'os_schedule_priority' setting.

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5858]
This setting will allow to control schedule priority of query execution threads with `nice` (or `pthread_setschedprio` or `setpriority` or `sched_setparam` or `sched_setattr`).

Caveats:
- it may not work as expected;
- it is not intended as proper implementation of resource sharing;
- as we use thread pool, we must reset priority when thread finished processing the query;

**Comment by akuzm** [comment]
I think it's worth to try it. We're going to have troubles with priority inversion, though. The first thing that comes to mind is DB::RWLock that is used to lock table structure for ALTERs. Fortunately we don't have many "heavyweight" locks such as row or table locks. In general, this is a problem for every synchronization primitive more complex than plain mutex, even for condition variables. I don't know CH internals enough to say which other resources are shared between queries and may require waiting.

We probably don't have to worry about IO prioritization, because on modern Linux the IO priority is inherited from thread priority.

To implement a nice-based prioritization, we must consider how CH works with threads. It does not create system threads directly for every query, but uses a thread pool named ThreadPoolGlobal. This pool consists of a number of threads that persist for the lifetime of the server process. These threads are used to execute jobs from a queue that is populated by the queries.
The job queue supports priorities, but apparently they are never used. These priority values go the other way, i.e. higher value means higher priority. This system should be integrated with the nice-based priority values, so that when an execution thread becomes available, we start with the most prioritized job.
The threading API used by the pool is std::thread. It doesn't have any knobs to control priority, but we can get an underlying pthread handle with native_handle(). Then we would set its priority with pthread_setschedprio(), getting the available range from sched_get_priority_min/max(). I'm not sure whether the same code is going to work on FreeBSD or Mac OS, and what is an unerlying object there. The actual priority value should be stored in ThreadGroupStatus.

Another relevant point is that CH already has a query priority system. Its implementation is pretty straightforward, though somewhat brutal: the query calls `sleep()` if there are any queries that have higher priority. The check happens each time the query reports progress. This system makes no attempt to prevent priority inversion, and we've had troubles before specifically with ALTERs [1]. Despite not being documented, this prioritization system has some users.

Using both systems at the same time makes little sense, so we could add a setting like `priority_backend = {sleep, nice}`, and make `priority` values compatible between these backends. Maybe even make them the same as Linux nice values {-20..19}, though I don't like the negatives and would prefer {0..39}.

1. https://nda.ya.ru/3VBiuB

P.S. After writing this, I realized that the Processors PR is going to completely change the way we schedule jobs, and it's unclear whether it is going to benefit from OS prioritization. We should probably wait for it and then reconsider.

**Comment by alexey-milovidov** [comment]
> The job queue supports priorities, but apparently they are never used.

This is priority of job to pick when thread pool is full. We cannot use it before "Processors" implementation because we schedule long-running jobs and we cannot postpone lower-priority queries for that time. More specifically, every query creates it's own private sub-pool and uses it exclusively.

> This system should be integrated with the nice-based priority values, so that when an execution thread becomes available, we start with the most prioritized job.

> Then we would set its priority with pthread_setschedprio(), getting the available range from sched_get_priority_min/max(). I'm not sure whether the same code is going to work on FreeBSD or Mac OS, and what is an unerlying object there. 

> Using both systems at the same time makes little sense, so we could add a setting like priority_backend = {sleep, nice}, and make priority values compatible between these backends. Maybe even make them the same as Linux nice values {-20..19}, though I don't like the negatives and would prefer {0..39}.

I prefer "worse is better" approach. We will introduce a new setting `os_schedule_priority` that will be completely unrelated and independent to `priority`. It will be directly mapped to `nice` value. We will not care about `sched_get_priority_min/max` because `nice` values are clamped to that interval. It will work only on Linux. ClickHouse postinstall script will try to enable CAP_SYS_NICE. PS. `nice` values and "realtime" priorities are different things. We will use `nice` values, because "realtime" priorities are more dangerous.

> native_handle()

We will use `gettid` that is syscall, but very cheap. With `native_handle` you only get `pthread_t` but cannot get `tid`.

**Comment by alexey-milovidov** [comment]
On a simple test, it works as expected:
```
24005 milovid+   0 -20 4181756 119460  75192 R 78.3  0.7   2:37.30 ParalInputsProc                                                                                                                                                       
24007 milovid+   0 -20 4181756 119460  75192 R 78.0  0.7   3:47.86 ParalInputsProc                                                                                                                                                       
23993 milovid+  20   0 4180732 119980  75192 D 59.5  0.7   3:37.04 ParalInputsProc                                                                                                                                                       
23994 milovid+  20   0 4180732 119720  75192 R 58.9  0.7   3:36.76 ParalInputsProc                                                                                                                                                       
24044 milovid+  39  19 4181756 119460  75192 R 26.3  0.7   1:10.41 ParalInputsProc                                                                                                                                                       
24046 milovid+  39  19 4181756 120240  75192 R 26.3  0.7   1:10.46 ParalInputsProc
```

But the difference between highest and lowest values is small.
