### ISSUE TITLE
/usr/bin/ld: cannot find -lanl

### ISSUE THREAD

**Issue by tqlihuiqi** [yandex/ClickHouse#61]
I try to install ClickHouse on CentOS7

Installation steps
    https://github.com/yandex/ClickHouse/blob/master/doc/build.md

error information is as follows:

/usr/bin/ld: cannot find -lanl
collect2: error: ld returned 1 exit status
make[2]: *** [contrib/libpoco/bin/f2cpsp] Error 1
make[1]: *** [contrib/libpoco/PageCompiler/File2Page/CMakeFiles/File2Page.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Looks like the ld command cannot find lanl library.

echo $LD_LIBRARY_PATH
/lib64:/usr/lib64:/usr/local/lib64:/usr/local:/usr/local/lib/mysql:/usr/lib

ls -l /usr/lib64/libanl.so
lrwxrwxrwx 1 root root 23 Jul 27 16:00 /usr/lib64/libanl.so -> ../../lib64/libanl.so.1

ls -l /lib64/libanl.so
lrwxrwxrwx 1 root root 23 Jul 27 16:00 /lib64/libanl.so -> ../../lib64/libanl.so.1

rpm -qf /lib64/libanl.so.1
glibc-2.17-106.el7_2.6.x86_64

**Comment by alexey-milovidov** [comment]
I have not investigate this issue yet. Also I have not tried to build on CentOS.
But there is another possibility to install ClickHouse on CentOS:

1. Temporarily obtain a server, VM or container with Ubuntu Trusty.
 
2. Build ClickHouse on Ubuntu Trusty according to the instructions: https://github.com/yandex/ClickHouse/blob/master/doc/build.md
but instead of ./release --standalone do GLIBC_COMPATIBILITY=1 ./release --standalone.
 
3. Install generated packages on target system with manual unpacking:
 
```
ar x clickhouse-server-base_1.1.53988_amd64.deb
sudo tar -x -C / -f data.tar.xz tar xf control.tar.gz
sed -r -i 's/update-rc.d.+/true;/' ./postinst
sudo ./postinst

ar x clickhouse-server-common_1.1.53988_amd64.deb
sudo tar -x -C / -f data.tar.xz

ar x clickhouse-client_1.1.53988_amd64.deb
sudo tar -x -C / -f data.tar.xz

sudo service clickhouse-server start 
```

**Comment by greenx** [comment]
For linker needed static library //-Bstatic -lanl
In openSUSE you need install package glibc-devel-static
In CentOs yum need install glic-staitc

**Comment by tqlihuiqi** [comment]
Thanks guys, I've already been installed ClickHouse on Centos7.

**Comment by jijiuzhou** [comment]
how to  installed ClickHouse on Centos7?
