### ISSUE TITLE
Do we need something like Zookeeper to replicate table?

### ISSUE THREAD

**Issue by linrl3** [yandex/ClickHouse#6109]
I just see some blogs saying that Zookeeper is required for replication, because <internal_replication>true</internal_replication> would cause problems for replication.

**Comment by masosky** [comment]
As far as I know, the answer is yes.
In order to synchronize replication, you must have a Zookeeper instance. Clickhouse recommends having at least 3 instances of Zookeeper in production.
Here, you can find a link that explain hard concepts in an easy way. Furthermore, you maybe find some answers about replication:
https://github.com/yandex/ClickHouse/issues/2161

I hope that it helps.

**Comment by filimonov** [comment]
Yes. To have reliable replication you need to install zookeeper & set internal_replication flag to true. 

Please read official documentation
https://clickhouse.yandex/docs/en/operations/table_engines/replication/

You can also check: 
https://blog.uiza.io/replicated-vs-distributed-on-clickhouse-part-1/
https://github.com/yandex/ClickHouse/issues/2161
https://www.altinity.com/blog/2017/6/5/clickhouse-data-distribution

You can also register to free webinar organized by Altinity on that subject next week:    
https://zoom.us/webinar/register/4015537115045/WN_QTKzs5B_Q_2fZv6eLnZNoQ
