### ISSUE TITLE
[Question] Kafka Engine Compression

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#6153]
Hello. 
I want to create the next schema of work with Clickhouse:
`c# client (that generate data in Clickhouse Native format) -> Kafka -> Clickhouse Table with Engine=Kafka.`
Such schema works.
But I want to add compression to this schema:
`c# client (that generate data in Clickhouse Native  format but with compression lz4) -> Kafka -> Clickhouse Table with Engine=Kafka.`
Is it possible, maybe with some parameters, create table in Clickhouse with Kafka Engine that will understand already compressed (with lz4) data from Kafka ?
Thanks in advance.

**Comment by alexey-milovidov** [comment]
No, it's not possible in current version.

**Comment by igor-sh8** [comment]
Thanks.
Maybe such functionality is planned in some upcoming versions ?

**Comment by igor-sh8** [comment]
Maybe Clickhouse can work with another archive formats (zstd, snappy, etc.) in a described schema ?

**Comment by filimonov** [comment]
Hm. I think that Kafka-side compression should work properly (i will try to check). I.e. if you will ask Kafka to compress the data - it will be stored used preferred algorithm and kafka client (rdkafka in ClickHouse case) should unpack messages properly. 

But it you will put into the Kafka messages which are already compressed (for example with clickhouse-compressor) ClickHouse will not unpack it.

**Comment by igor-sh8** [comment]
Hi. 
We used for our schema compression settings on the producer side and `compression.type=producer` on the broker side. 
And it works (Clickhouse can work with such data). 
Thanks for help.

**Comment by JForsaken** [comment]
For those that want the compression done on the producer side directly, it is now possible since this commit:
https://github.com/ClickHouse/ClickHouse/pull/58956/files#diff-8a65ed88620ac5ef2253eb77a159f9b788d13860393c44db27a1c45846e3e7f0

Since the producer and consumer configurations are now separated, you can now pass `LibRdKafka` settings as XML in the Clickhouse `config.xml` (or your personal `.xml` override file).

I've tested this by first adding:
```
  <kafka>
      <producer>
        <compression_codec>lz4</compression_codec>
        <message_max_bytes>52428800</message_max_bytes>
      </producer>
  </kafka>
```
Then grepping `Producer` in the `clickhouse-server.log` file, since in the commit above we see that `TRACE` logs are emitted when setting properties on the producer & consumer:
```
<Trace> StorageKafka (some_kafka_table): Producer set property message.max.bytes:54272000
<Trace> StorageKafka (some_kafka_table): Producer set property compression.codec:lz4
```

This confirms that the `LibRdKafka` settings from the `.xml` Clickhouse config files are forwarded to `LibRdKafka`.

To really make sure those were applied, especially the compression codec, I've ran:
```bash
/bin/kafka-run-class kafka.tools.DumpLogSegments \
    --files /tmp/kraft-combined-logs/my-topic-0/00000000000000000000.log \
    --print-data-log \
    --deep-iteration
```

Which outputs:
```
baseOffset: 5 lastOffset: 5 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false deleteHorizonMs: OptionalLong.empty position: 673 CreateTime: 1739225436138 size: 120 magic: 2 compresscodec: lz4 crc: 3085245213 isvalid: true
| offset: 5 CreateTime: 1739225436138 keySize: -1 valueSize: 229 sequence: -1 headerKeys: [] payload: {"some_data":"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}
```

As we can see, the `compresscodec` above is `lz4`, with a compressed size of `120` and a decompressed size of `229`!

I think this (forwarding LibRdKafka settings from the Clickhouse the config file) should be documented @alexey-milovidov , since I didn't know it was possible without seeing the commit from above -- pretty sure there's a lot of people wondering the same!
