### ISSUE TITLE
Is large partition size ok? Is it worth to go from toDate to toStartOfHour within PARTITION BY?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#6199]
I was trying to find any info on this topic in https://clickhouse.yandex/docs/en/operations/table_engines/custom_partitioning_key/ but without success.

My problem is (?) that partitions with `PARTITION BY toDate(dt_column)` are over 600G in size. I think it's too high so I'm trying to determine proper `PARTITION BY` clause. I was thinking that simply changing `toDate()` to `toStartOfHour()` should do the trick and lower the partitions size while increasing their count x24.

1. Is it actually a issue to have large partition size?
2. Having 24 partitions per day instead of 1 doesn't seem like much of a difference, it is?

Could anyone elaborate on this topic? Thanks!

**Comment by alexey-milovidov** [comment]
> Is it actually a issue to have large partition size?

No, it's not an issue. You will have higher number of data parts inside partition, because ClickHouse limits the size of a single data part to 150 GB by default.

The system is designed in a way that you can even have single partition (a table without `PARTITION BY`) in arbitrary size table.

> Having 24 partitions per day instead of 1 doesn't seem like much of a difference, it is?

Unless you store data for longer time interval and you will have too many partitions. For example, if you have 100 TB of storage per server, you will have maximum 167 partitions with daily partitioning (that's fine) and 4000 partitions with hourly partitioning (that's less fine).

**Comment by simPod** [comment]
Thanks a lot for clarification!
