### ISSUE TITLE
Why MergeTree  need Data column?

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#642]
create table SQL:
```
CREATE TABLE events_local
(
    src_ip UInt32,
    dest_ip UInt32,
    src_port UInt16,
    dest_port UInt16,
    req_time UInt64,
    page_urlhost String,
    page_urlpath String,
    page_full_url String,
    resp_size UInt64,
    content_type String
) ENGINE = MergeTree(intHash64(src_ip), intHash64(req_time), (dest_ip, src_port, dest_port, req_time, page_urlhost, page_urlpath, page_full_url, resp_size, content_type, src_ip), 8192)
```
I can't create success. error log is need Data&primary key column. 
I can't find any about primary key info,This is table don't need Data type column.
How to fixed this problem.

**Comment by DenisCheremisov** [comment]
You need Date (not Data, it is Date, i.e. day, '2017-03-30' for instance), because MergeTree engine splits data into partitions by months, and the engine obviously needs a way to know what date a record belongs to and it only was taught to use Date typed field for the purpose.
So, you need a Date typed field in  table, like
```sql
CREATE TABLE testTables (
    date Date,
    value String
) ENGINE=MergeTree(date, (value), 8192);
```

**Comment by ludv1x** [comment]
FYI You can create dummy date filed (which you will not use into INSERT and SELECT queries).
In that case all table's data belong to the same partition (with name `197001`), but such commands as `FREEZE PARTITION`, `DROP PARTITION`, etc does not make sense.

**Comment by sangli00** [comment]
so,If i create dummy date,Data is not balance in every node.
