### ISSUE TITLE
Partial data in MySQL dictionaries when close_connection is set to 1

### ISSUE THREAD

**Issue by SaltTan** [yandex/ClickHouse#6825]
**Describe the bug**
When `close_connection` is set to 1 for a MySQL dictionary, CH loads only 8192 rows into the dictionary.

**How to reproduce**
19.13.3.26 is affected, bit I think it never worked.
A MySQL table with more than 8192 rows is needed to reproduce the issue.
An example of a dictionary:
```
    <dictionary>
        <name>table</name>
        <source>
            <mysql>
                <host>host</host>
                <port>3306</port>
                <user>user</user>
                <password>password</password>
                <db>db</db>
                <table>table</table>
                <close_connection>1</close_connection>
            </mysql>
        </source>
        <lifetime>60</lifetime>
        <layout><flat/></layout>
        <structure>
            <id>
                <name>key</name>
            </id>
            <attribute>
                <name>name</name>
                <type>String</type>
                <null_value/>
            </attribute>
        </structure>
    </dictionary>

```

**Comment by clemrodriguez** [comment]
This bug is indeed coming from #5395 .
MySQL connection is closed at end of readImpl method even if there are still Block to come after the current one is full in object dbm>Formats>MySQLBlockInputStream.cpp
Removing connection closure at lines 133 & 134, fix the issue (locally reproduced and fixed).
Proposed fix still permits to have MySQL connection closed but only when the last row was read.

[MySQLBlockInputStream.cpp.txt](https://github.com/yandex/ClickHouse/files/3590719/MySQLBlockInputStream.cpp.txt)

Regards

**Comment by filimonov** [comment]
@clemrodriguez can you create a PR to review the change?
