### ISSUE TITLE
system.processes show negative memory_usage for RENAME TABLE queries

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#695]
```
 :) SELECT *, formatReadableSize(memory_usage) AS mem_used FROM system.processes FORMAT Vertical;

...
http_method:          2
http_user_agent:      python-requests/2.11.1
elapsed:              0.820777534
...
memory_usage:         -131439
query:                RENAME TABLE table TO table_old\n
mem_used:             -128.36 KiB
```

**Comment by alexey-milovidov** [comment]
That looks strange, but in fact, it is reasonable.

Memory usage for query shows difference between sizes of memory allocations and deallocations, that was made in context of query execution.
Usually, they are balanced: what was allocated during query execution, will be subseqently freed and so on.

But there are some exceptions. For example, the query could load some data and leave it in cache (marks cache, uncompressed cache). In that case, it will allocate memory in its context, but memory will be freed later, outside of query context.

Similarly, if some data was evicted from cache during query execution, it is accounted as memory deallocation, and query memory usage could become negative.

RENAME query does cache flush, because cache items are addressed by table path, that is dependent on table name. That's why it has negative memory usage.

Nevertheless, we decided to remove such behaviour, because reported numbers of memory usage could become totally inadequate for long running INSERT queries or for background merges. I already commited a fix few days ago and it is scheduled for next release.
