### ISSUE TITLE
how to  recover the data in detach directory

### ISSUE THREAD

**Issue by yunding** [yandex/ClickHouse#6993]
there are some part data in detach how i can i recover these data ?

**Comment by yunding** [comment]
the data directory like ignored_20190709_1820_1835_3_4416

**Comment by filimonov** [comment]
Please try to find the reason in logs why it was ignored. It may be covered by other parts and you don't need to do anything.

Otherwise - create the table with the same structure as original, put that part into the `detached` folder for that new table (removing `ignored_` prefix), and do `alter table ... attach part`

**Comment by yunding** [comment]
attach part seems not work. I found the partition_id in system.detached_parts and execute alter table attach partition id ... at last the data recover! thanks you

**Comment by den-crane** [comment]
ignored_  parts are inactive parts not deleted because of CH spontaneous reboot.
When you attaching them you making duplicates of existing data.
